// Phase 5 copy: Loans, repayment calculator, Offers, Hardship, Help, Account, Notifications (en-AU).
// Numbers come from selectors; these functions only word them.

export const loansPage = {
  title: "Loans",
  search: "Search loan transactions",
  tabsLabel: "Loans views",
  tabs: { overview: "Overview", upcoming: "Upcoming", history: "History", other: "Other credit" },
  dti: (pct: string) => `Debt repayments are about ${pct} of income.`,
  dtiNote: "Over the last 90 days. Includes loans, buy now pay later and pay advances.",
  loansHeading: "Loans",
  totalLeft: (amt: string) => `About ${amt} left across your loans, estimated`,
  noLoans: "We didn't find any loans in the connected account.",
  bnplHeading: "Buy now, pay later",
  advanceHeading: "Pay advance",
  perCadence: (amt: string, cadence: string) => `${amt} ${cadence}`,
  cadence: (days: number | null) => (days === null ? "each repayment" : days >= 28 ? "per month" : days >= 13 && days <= 15 ? "per fortnight" : days === 7 ? "per week" : `every ${days} days`),
  balanceUnavailable: "Balance not available",
  received: (amt: string, date: string) => `${amt} received ${date}`,
  estimated: "estimated from your transactions",
  viewRepayments: "View repayments",
  nextDue: (date: string) => `Next due ${date}`,
  calculatorLink: "Work out an early repayment",
  offersLink: "Offers from partner lenders",
  upcoming: {
    rangeLabel: "Show the next",
    ranges: { 30: "30 days", 60: "60 days", 90: "90 days" },
    total: (amt: string, days: number) => `About ${amt} in the next ${days} days`,
    note: "Predicted from past repayments. Your lender's schedule is the one that counts.",
    empty: "No repayments expected in this period.",
    predicted: "predicted",
  },
  history: {
    month: (label: string, amt: string) => `${label} · ${amt}`,
    failedHeading: "Payments that didn't go through",
    failed: (lender: string | null, date: string, fee: string) => `${lender ? `${lender} direct debit` : "A direct debit"} on ${date}. Bank fee ${fee}.`,
    noFailed: "No failed payments in the history we have.",
    empty: "No repayments in the history we have.",
  },
  other: {
    intro: "Credit that isn't a loan: buy now pay later, pay advances and credit cards.",
    cards: "Credit cards",
    noCards: "We didn't find a credit card in the connected account. If you have one with another bank, connect that account too.",
    none: "No buy now pay later or pay advances found.",
  },
} as const;

export const calculatorPage = {
  title: "Early repayment",
  intro: "See what paying a bit extra each pay cycle could do. TaleFin can't see your loan's rate or term, so check these details against your lender's statement.",
  loanLabel: "Loan",
  balanceLabel: "Balance left",
  balanceHint: "Our estimate from your transactions. Your lender can tell you the exact figure.",
  balanceHintShared: (amt: string) => `Your small loans have about ${amt} left between them. Enter this loan's share from your lender's statement.`,
  repaymentLabel: "Regular repayment",
  rateLabel: "Interest rate (% a year)",
  rateHint: "Leave at 0 if your loan only charges fees.",
  feeLabel: "Monthly fee",
  feeHint: "Small loans often charge a monthly fee instead of interest.",
  extraLabel: "Extra each pay cycle",
  extraValue: (amt: string) => `${amt} extra each pay cycle`,
  lumpLabel: "One-off extra payment now",
  lumpHint: "Pro: try a one-off payment as well.",
  resultHeading: "What it would change",
  sooner: (n: number) => (n === 1 ? "Paid off about 1 week sooner" : `Paid off about ${n} weeks sooner`),
  noSooner: "Add an extra amount to see the difference.",
  saved: (amt: string) => `About ${amt} less in interest and fees`,
  noSaving: "No interest or fees to save with the details entered.",
  current: (weeks: number, date: string) => `At the current repayment: about ${weeks} weeks, paid off around ${date}.`,
  withExtra: (weeks: number, date: string) => `With the extra: about ${weeks} weeks, paid off around ${date}.`,
  never: "At this repayment the balance doesn't go down, because interest and fees are more than the repayment. Your lender can help, or see Hardship support.",
  basedOn: "Based on the details you entered.",
  invalid: "Enter an amount like 96 or 96.50",
  pickLoan: "Choose a loan",
  noLoans: "There are no loans to work out. If you have a loan with another bank, connect that account.",
  hardship: "Options if money's tight",
} as const;

export const offersPage = {
  title: "Offers",
  info: "How matching works",
  infoBody: [
    "With lender matching on, partner lenders can see a summary of your Tippla profile when you might qualify for a loan.",
    "They never see your transactions or anything about your health, family or circumstances. You can turn matching off at any time.",
    "Matching is not approval. The lender makes its own assessment.",
  ],
  sample: "(sample)",
  off: {
    title: "Lender matching is off",
    body: "Offers only appear if you let partner lenders see your profile when you might qualify. Tippla works the same either way.",
    action: "Manage lender matching",
  },
  none: "No offers right now. Tippla checks for you every time your data refreshes. You don't need to do anything.",
  dismissed: (lender: string) => `${lender} hidden. We won't show this offer again`,
  detailsTitle: (lender: string) => `${lender} offer`,
  detailsWhatNext: "What happens next",
  detailsNext: [
    "In the live app, this is where you'd go to the lender's own site to read the full terms and apply.",
    "Nothing is sent to the lender until you choose to apply there. Tippla doesn't apply for you.",
  ],
  detailsHandoff: "Lender hand-off isn't part of this prototype.",
  close: "Close",
  notInterestedHint: "Hiding an offer doesn't turn off lender matching.",
} as const;

export const hardshipPage = {
  title: "Hardship support",
  sub: "Support, on your terms",
  opener: "If money's tight right now, these are real options.",
  scoreNote: "Using them doesn't count against your SmartScore.",
  info: "About this page",
  infoBody: [
    "Everything here is optional. Tippla doesn't tell lenders you've visited this page or used any of these options.",
  ],
  lender: { title: "Ask your lender for a hardship arrangement", body: "A message you can make your own.", action: "Use message template" },
  counselling: { title: "Free financial counselling", body: "National Debt Helpline", action: "See ways to get in touch" },
  tippla: { title: "Pause or downgrade Tippla", body: "Choose what works for you.", action: "Manage subscription" },
  gambling: { title: "Gambling support options", body: "Tools and support, if you want them.", action: "View support options" },
  template: {
    title: "Ask about hardship",
    intro: "Edit this message, then copy it to send to your lender.",
    label: "Your message",
    body: "Hi [lender],\n\nI'm having trouble keeping up with my repayments. I'd like to ask about a hardship arrangement.\n\nCould you let me know what options are available and what information you need from me?\n\nPlease contact me by [preferred contact method].\n\nThank you,\n[name]",
    copy: "Copy message",
    copied: "Message copied",
    copyFailed: "Couldn't copy automatically. Select the text and copy it yourself.",
    cancel: "Cancel",
    yourLenders: (names: string) => `Your lenders, from your transactions: ${names}.`,
  },
  ndh: {
    title: "Free financial counselling",
    name: "National Debt Helpline",
    body: "Talk through your options with a financial counsellor. It's free and confidential.",
    call: (num: string) => `Call ${num}`,
    visit: "Visit National Debt Helpline",
    visitNote: "ndh.org.au · contact options and hours",
    notNow: "Not now",
  },
  notNow: "Not now",
} as const;

export const helpPage = {
  title: "Help",
  searchLabel: "Search help",
  searchPlaceholder: "Search, for example: declined",
  results: (n: number) => (n === 1 ? "1 answer" : `${n} answers`),
  empty: (q: string) => `No answers match "${q}". Try another word, or contact us.`,
  contact: "Contact Tippla",
  contactTitle: "Contact Tippla",
  contactBody: "In the live app this opens a message to the Tippla support team, who reply by email within one business day. Messaging isn't part of this prototype.",
  hardshipLink: "If money's tight right now, see Hardship support",
  accountHeading: "Account and settings",
  accountLinks: { profile: "Profile and notifications", subscription: "Subscription and billing", consents: "Consents and lender matching", bank: "Bank connections" },
  faqs: [
    {
      id: "declined",
      q: "Why was I declined?",
      a: "Friendly Finance makes its own decision, and Tippla doesn't see its reasons. Lenders usually look at the same kinds of things your SmartScore does: how steady your income is, how much is left after bills, how many loans you have, and whether payments go through. Your SmartScore page shows which of these has the most room to move.",
      links: [{ href: "/score", label: "See your SmartScore" }],
    },
    {
      id: "credit",
      q: "Will checking my score hurt my credit?",
      a: "No. Your SmartScore comes from your bank data through TaleFin, not a credit enquiry. Checking it doesn't appear on your credit file, however often you look.",
      links: [],
    },
    {
      id: "data",
      q: "Who sees my data?",
      a: "Tippla and TaleFin, to work out your SmartScore and show you your spending. Partner lenders see a summary of your profile only if you turn on lender matching, and never your transactions or anything about your health, family or circumstances.",
      links: [{ href: "/account/consents", label: "Review your consents" }],
    },
    {
      id: "contact",
      q: "How do I stop lenders contacting me?",
      a: "Turn off lender matching in Consents. Lenders then can't see your profile, and offers stop appearing. Tippla doesn't give lenders your phone number or email.",
      links: [{ href: "/account/consents", label: "Manage lender matching" }],
    },
    {
      id: "cancel",
      q: "How do I cancel?",
      a: "Go to Subscription and billing and choose Cancel subscription, then confirm. That's it. You keep access until the end of the period you've paid for.",
      links: [{ href: "/account/subscription", label: "Subscription and billing" }],
    },
    {
      id: "income",
      q: "Why is my income wrong?",
      a: "We work out your monthly income from the last 90 days of regular pay into the accounts you've connected, and leave out one-off deposits and pay advances. If some of your pay goes into another account, connect that account too.",
      links: [{ href: "/account/bank", label: "Bank connections" }],
    },
    {
      id: "banks",
      q: "I changed banks",
      a: "Connect your new bank in Bank connections. Your history builds up from there. You can keep the old account connected, or disconnect it once you've stopped using it.",
      links: [{ href: "/account/bank", label: "Bank connections" }],
    },
  ],
} as const;

export const accountPage = {
  title: "Account",
  menu: "Account",
  sections: { profile: "Profile and notifications", subscription: "Subscription and billing", consents: "Consents", bank: "Bank connections" },
  profile: {
    title: "Profile",
    details: "Your details",
    name: "Name",
    email: "Email",
    mobile: "Mobile",
    edit: "Edit",
    editTitle: (field: string) => `Edit ${field.toLowerCase()}`,
    save: "Save",
    saved: (field: string) => `${field} updated`,
    channelsHeading: "Notifications",
    channelsIntro: "Choose how you hear about each thing. You can change this any time.",
    channels: { email: "Email", push: "Push" },
    types: { money: "Shortfalls and bills bigger than your balance", payday: "Payday check-in and pay-cycle recap", score: "SmartScore updates", subscription: "Subscription and billing", bank: "Bank connection" },
    eventsOnly: "We only send a notification when something happens with your money. Never offers, and nothing about gambling or alcohol.",
    policy: "At most one notification a day, plus one urgent money alert, and three a week. Anything over that waits in your notifications here.",
    pauseAll: "Pause all notifications",
    pauseNote: "Nothing is sent while paused. Everything still appears in your notifications here.",
    quietHeading: "Quiet hours",
    quietFrom: "From",
    quietTo: "Until",
    quietNote: "Nothing buzzes your phone between these times. Urgent money alerts wait until then too, unless the thing is due first.",
    detailed: "Show amounts and names on my lock screen",
    detailedNote: "Off: your lock screen just says \"You have an update from Tippla\".",
    digest: "Weekly summary for SmartScore updates",
    digestNote: "Sent on Sundays instead of one at a time. Shortfalls, bills and payday come straight away.",
    time: (hhmm: string) => { const h = Number(hhmm.slice(0, 2)); return `${h % 12 === 0 ? 12 : h % 12}${hhmm.slice(2) === ":00" ? "" : hhmm.slice(2)}${h < 12 ? "am" : "pm"}`; },
    notifySaved: "Notification settings saved",
    offerNeedsMatching: "Only sent when lender matching is on.",
    readOnly: "To change your name, contact Tippla.",
    invalidEmail: "Enter an email address like name@example.com",
    invalidMobile: "That mobile number needs 10 digits, starting with 04",
    insightsHeading: "Insights",
    gamblingLabel: "Show gambling insights",
    gamblingNote: "Off: we won't mention gambling in your insights or score explanations. Your SmartScore is worked out the same way, and gambling support is always in Help.",
    gamblingSaved: (on: boolean) => (on ? "Gambling insights on" : "Gambling insights off"),
    usageHeading: "Usage data",
    usageLabel: "Share anonymous usage data to help improve Tippla",
    usageNote: "We record which screens and features you use, linked to a code rather than your name. Never amounts, merchant names or anything you type. You can turn this off any time.",
    usageSaved: (on: boolean) => (on ? "Usage data on" : "Usage data off. We won't record anything from now on."),
    themeHeading: "Appearance",
    theme: { system: "Match my device", light: "Light", dark: "Dark" },
  },
  subscription: {
    title: "Subscription and billing",
    plan: (name: string) => `${name} plan`,
    price: (amt: string) => `${amt} a month`,
    nextCharge: (date: string) => `Next charge ${date}`,
    cancelledUntil: (date: string) => `Cancelled. You can use Tippla until ${date}, and you won't be charged again.`,
    pausedUntil: (date: string) => `Paused. Billing resumes on ${date}.`,
    pendingPlan: (name: string, date: string) => `Changing to ${name} on ${date}.`,
    includes: "Both plans include everything in Tippla. Pro adds:",
    changePlan: (name: string) => `Change to ${name}`,
    changeTitle: (name: string) => `Change to ${name}`,
    changeBody: (name: string, price: string, date: string) => `From ${date} you'll be on ${name} at ${price} a month. Until then nothing changes.`,
    changeConfirm: (name: string) => `Change to ${name}`,
    changed: (name: string, date: string) => `Changing to ${name} on ${date}`,
    keepPlan: "Keep my plan",
    cancel: "Cancel subscription",
    cancelTitle: "Cancel your subscription?",
    cancelBody: (date: string) => `You won't be charged again. You can keep using Tippla until ${date}.`,
    cancelConfirm: "Yes, cancel",
    cancelled: "Subscription cancelled",
    pauseInstead: "Pause instead",
    pauseTitle: "Pause your subscription?",
    pauseBody: (skip: string, resume: string) => `Your ${skip} charge is skipped and billing resumes on ${resume}. Your SmartScore and spending won't refresh while paused. You can resume any time.`,
    pauseConfirm: "Pause",
    paused: "Subscription paused",
    resume: "Resume subscription",
    resumed: "Subscription resumed",
    reactivate: "Keep my subscription",
    reactivated: "Subscription kept",
    back: "Go back",
    history: "Billing history",
    paid: "Paid",
    noHistory: "No charges yet.",
    status: { active: "Active", paused: "Paused", cancelled: "Cancelled" },
    // Spec 03: billing on payday.
    nextChargeAfterPayday: (date: string) => `Next charge ${date} (the day after your payday)`,
    nextChargeAmount: (amt: string, date: string, afterPayday: boolean) => `Next charge ${amt} on ${date}${afterPayday ? " (the day after your payday)" : ""}`,
    moved: (payday: string) => `We've moved your Tippla payment to after your pay lands on ${payday}.`,
    deferred: (from: string, to: string) => `We've moved your payment from ${from} to ${to}, after your pay lands, so it doesn't take your balance below $0.`,
    proration: (amt: string, from: string, to: string, days: number, price: string, period: number) =>
      `Because the date moved, this charge includes ${amt} for ${from} – ${to} (${days} ${days === 1 ? "day" : "days"} × ${price} ÷ ${period} days).`,
    credit: (amt: string, days: number) => `Because the date moved earlier, this charge is ${amt} less (${days} ${days === 1 ? "day" : "days"} you'd already paid for).`,
    failed: (amt: string, on: string, retry: string) => `Your ${amt} payment on ${on} didn't go through. We'll try again on ${retry}, after your pay lands. There's no fee from Tippla.`,
    failedLast: (amt: string, on: string) => `Your ${amt} payment on ${on} didn't go through. We won't try again: you can pay it whenever suits you, or pause your subscription.`,
    whenHeading: "When we charge you",
    afterPayday: "The day after payday (recommended)",
    fixedDate: "A fixed date each month",
    dayLabel: "Day of the month",
    day: (n: number) => `${n}${n % 10 === 1 && n !== 11 ? "st" : n % 10 === 2 && n !== 12 ? "nd" : n % 10 === 3 && n !== 13 ? "rd" : "th"}`,
    fixedNote: "If a charge on that date would take your balance below $0 before your next pay, we'll move it to after your pay lands.",
    howOften: "How often",
    monthly: (price: string) => `Monthly (${price})`,
    perCycle: (price: string) => `Each pay cycle (${price} a fortnight)`,
    perCycleNote: "The same over a year: the monthly price × 12 ÷ 26.",
    prefSaved: "Payment settings saved",
    pauseNow: "Pause for a month",
    tight: "If money's tight, you can pause for a month or change plan. Nothing is hidden behind cancelling.",
  },
  consents: {
    title: "Consents",
    intro: "What you've agreed to, and when. Required ones are needed for Tippla to work.",
    required: "Required",
    optional: "Optional",
    given: (date: string) => `Given ${date}`,
    notGiven: "Not given",
    version: (v: string) => `Version ${v}`,
    on: "On",
    off: "Off",
    matchingPaused: "Lender matching is paused. Lenders won't see your profile.",
    matchingOn: "Lender matching is on. Partner lenders can see a summary of your profile when you might qualify.",
    withdrawRequiredTitle: "Withdraw this consent?",
    withdrawRequiredBody: "Tippla can't work without it. Withdrawing it closes your account, and in the live app you'd be taken through that. Closing accounts isn't part of this prototype.",
    close: "Close",
    undo: "Undo",
  },
  bank: {
    title: "Bank connections",
    intro: "Accounts Tippla reads through TaleFin. Read-only: Tippla can't move money.",
    account: (name: string, last4: string) => `${name} ··${last4}`,
    refreshed: (when: string) => `Last refreshed ${when}`,
    refresh: "Refresh now",
    refreshing: "Refreshing",
    refreshDone: "Bank data refreshed",
    reconnect: "Reconnect",
    add: "Connect another account",
    addNote: "If you're paid into another account, connecting it makes your income and spending more complete.",
    disconnect: "Disconnect",
    disconnectTitle: "Disconnect this bank?",
    disconnectBody: "Your SmartScore and spending stop updating. What you already see stays until you reconnect.",
    disconnectConfirm: "Disconnect",
    disconnected: "Bank disconnected",
    disconnectedNote: "Disconnected. Your numbers have stopped updating.",
    reconnectTitle: "Reconnect your bank",
    reconnectBody: "In the live app you'd sign in to your bank through TaleFin, the same way as when you joined. In this prototype, Continue reconnects straight away.",
    addTitle: "Connect another account",
    addBody: "In the live app this opens TaleFin so you can choose another bank or account. Connecting more accounts isn't part of this prototype.",
    continue: "Continue",
    reconnected: "Bank reconnected",
    cancel: "Cancel",
  },
} as const;

export const notificationsCopy = {
  title: "Notifications",
  groups: { today: "Today", week: "This week", earlier: "Earlier" },
  markAll: "Mark all as read",
  unread: "Unread",
  settings: "Notification settings",
  empty: "No notifications yet. We only send one when something happens with your money.",
  badge: (n: number) => (n === 1 ? "1 unread notification" : `${n} unread notifications`),
  delivery: {
    push: "Sent to your phone",
    email: "Sent by email",
    inbox: "Kept here (you'd reached your daily limit)",
    digest: "In your weekly summary",
    paused: "Kept here (notifications are paused)",
    off: "Kept here (you've turned these off)",
  },
  shortfall: {
    title: (amt: string) => `Heads up: about ${amt} short before payday`,
    body: (date: string) => `Your balance looks like going under on ${date}. There are options if money's tight.`,
    overdrawn: "Your account is overdrawn and there are still bills before payday. There are options if money's tight.",
  },
  billTomorrow: {
    title: (m: string, amt: string) => `${m} ${amt} is due tomorrow`,
    body: (bal: string) => `That's more than the ${bal} we expect in your account. It may not go through in full.`,
    overdrawn: "Your account is overdrawn, so it may not go through in full. There are options if money's tight.",
  },
  payday: {
    title: (amt: string) => `Payday: ${amt} landed`,
    body: (safe: string | null, bills: number) => `${safe ? `Safe to spend: about ${safe} a day. ` : ""}${bills === 1 ? "1 bill" : `${bills} bills`} before next payday.`,
    nothingSpare: (bills: number) => `${bills === 1 ? "1 bill" : `${bills} bills`} before next payday take most of it. Your check-in has the details.`,
  },
  recap: {
    title: "Your last pay cycle, in a minute",
    body: (spent: string, paidIn: string, streak: string) => `${spent} spent, ${paidIn} paid in.${streak ? ` ${streak}` : ""}`,
    noAdvance: (n: number) => (n <= 1 ? "No new pay advance." : `No new pay advance, ${n} pay cycles in a row.`),
  },
  score: {
    title: (score: number) => `Your SmartScore is ${score}`,
    body: (delta: number, since: string) => (delta === 0 ? `No change since ${since}.` : `${delta > 0 ? "Up" : "Down"} ${Math.abs(delta)} since ${since}. See what changed.`),
    pendingTitle: "Your SmartScore is on its way",
    pendingBody: "We need a bit more history. We'll let you know when it's ready.",
  },
  subscription: {
    cancelled: "Your subscription is cancelled",
    cancelledBody: (date: string) => `You can use Tippla until ${date}.`,
    paused: "Your subscription is paused",
    pausedBody: (date: string) => `Billing resumes on ${date}.`,
  },
  bank: {
    disconnected: "Bank disconnected",
    disconnectedBody: "Your numbers have stopped updating. Reconnect any time.",
  },
} as const;
