// Spec 06 copy: hardship letter, cancellation helper additions, bill comparison pointers and the
// entitlements check. General information only; nothing here is advice or a promise of eligibility.
export const letterCopy = {
  title: "Ask your lender for a hardship arrangement",
  start: "Write my letter",
  stepDetails: "Check the details",
  stepQuestions: "A bit about what's changed (optional)",
  stepLetter: "Your letter",
  intro: "We've filled in what we can see. Change anything that's not right.",
  lender: "Lender",
  amount: "Repayment ($)",
  due: "Due date",
  name: "Your name",
  reasonLabel: "What's changed?",
  reasons: { job_loss: "I lost my job", reduced_hours: "My hours were cut", illness: "Illness or injury", family: "A change in my family", other: "Something else" } as Record<string, string>,
  durationLabel: "How long do you expect it to last?",
  durations: { weeks: "A few weeks", months: "A few months", unsure: "I'm not sure yet" } as Record<string, string>,
  affordLabel: "What could you pay each fortnight? ($, optional)",
  contactLabel: "How should they contact you? (optional)",
  next: "Next",
  back: "Back",
  skip: "Skip",
  editLabel: "Your letter (you can edit it)",
  copy: "Copy",
  email: "Open in email",
  pdf: "Download PDF",
  copied: "Letter copied",
  neverSends: "Tippla never sends this for you. You choose when and how to send it.",
  contactKnown: (how: string) => `Send it to: ${how}`,
  contactUnknown: (lender: string) => `Look for "hardship" on ${lender}'s website or app, or call their customer line and ask for the hardship team.`,
  law: "Under Australian credit law, lenders must consider a hardship request. This is general information, not legal advice.",
  subject: (lender: string) => `Hardship request: ${lender} repayment`,
  /** Assembled in plain English; every part after the first paragraph is optional. */
  body: {
    greeting: (lender: string) => `Hi ${lender},`,
    ask: (amount: string, due: string) => `I'm having trouble keeping up with my repayments, including the ${amount} due on ${due}. I'd like to ask for a hardship arrangement.`,
    reason: { job_loss: "I recently lost my job.", reduced_hours: "My working hours have been cut.", illness: "I've been affected by illness or injury.", family: "There's been a change in my family circumstances.", other: "My circumstances have changed." } as Record<string, string>,
    duration: { weeks: "I expect this to last a few weeks.", months: "I expect this to last a few months.", unsure: "I'm not sure yet how long this will last." } as Record<string, string>,
    afford: (amt: string) => `I could afford to pay about ${amt} a fortnight for now.`,
    options: "Could you let me know what options are available and what information you need from me?",
    contact: (how: string) => `Please contact me by ${how}.`,
    close: "Thank you,",
  },
  followup: {
    title: (lender: string) => `Did you hear back from ${lender}?`,
    body: "About your hardship request. Your answer helps us show the right next step.",
    action: "Answer",
    answers: { agreed: "Yes, they agreed", declined: "Yes, they said no", not_yet: "Not yet" } as Record<string, string>,
    agreed: "That's good news. We'll keep your forecast up to date with any new repayment amounts once they show in your bank.",
    declined: "That's hard. A free financial counsellor at the National Debt Helpline can help you ask again or look at other options.",
    notYet: "Lenders usually reply within 21 days. We'll ask again next pay cycle.",
    sheetTitle: "Your hardship request",
  },
};

export const cancelExtraCopy = {
  stillUsing: (m: string) => `Still using ${m}?`,
  yes: "Yes",
  no: "No",
  openCancelPage: (m: string) => `Open ${m}'s cancel page`,
  opensInNewTab: "(opens in a new tab)",
  nextCharge: (next: string) => `The next charge is expected around ${next}.`,
  stepsChange: (m: string) => `Steps can change. If something looks different, check ${m}'s help pages.`,
  failedTitle: (m: string) => `${m} charged again: the cancellation may not have gone through`,
  failedBody: (amt: string, date: string) => `We saw ${amt} on ${date}. It's worth checking your account with them.`,
  failedAction: "See how to cancel",
};

export const billSwitchCopy = {
  heading: "Compare your bills",
  intro: "General information to help you compare. We don't recommend providers or get paid for referrals.",
  categories: { telco: "Phone", internet: "Internet", energy: "Energy" } as Record<string, string>,
  line: (merchant: string, amt: string) => `${merchant}: about ${amt} a month`,
  energy: "Compare energy plans for your area on Energy Made Easy, the government's comparison site.",
  energyVic: "In Victoria, Victorian Energy Compare is the government's comparison site.",
  telco: "Providers often have newer plans with the same data for less. Ask your provider which of their current plans suits your usage, or compare a few providers' plans yourself.",
  compare: "Compare on Energy Made Easy",
  tipsTitle: (merchant: string) => `Paying less for ${merchant}`,
  tips: ["Check how much data or calls you actually use: your bill or app shows it.", "Ask your provider for their current plans at that level, and whether you can move without a fee.", "Look at a few other providers' plans for the same usage before deciding."],
  switched: "I've switched or changed plan",
  savedLabel: "About how much less each month? ($)",
  save: "Save",
  reported: (amt: string) => `Noted: about ${amt} a month less (you told us)`,
  selfReported: "you told us",
  reportedHeading: "You told us (not counted in the total)",
  reportedLine: (m: string, amt: string) => `${m}: about ${amt} a month less after switching`,
  invalid: "Enter an amount between $1 and $500",
  general: "General information only. It doesn't take your full situation into account.",
};

export const entitlementsCopy = {
  title: "Support you might be able to get",
  intro: "A few optional questions, then pointers to official sites where you can check. Tippla doesn't decide whether you're eligible.",
  general: "General information only. Only the official site can tell you what you can get.",
  feedTitle: "Check support you might be able to get",
  feedBody: "A few quick questions, then links to official sites. Optional, and only you see your answers.",
  feedAction: "Start the check",
  q: {
    household: { label: "Who lives with you?", options: { alone: "Just me", partner: "Partner", kids: "Children", shared: "Housemates" } as Record<string, string> },
    dependants: { label: "Does anyone rely on you financially?", options: { yes: "Yes", no: "No" } as Record<string, string> },
    work: { label: "What's your work situation?", options: { full: "Full-time", part: "Part-time or casual", looking: "Looking for work", none: "Not working" } as Record<string, string> },
    study: { label: "Are you studying?", options: { yes: "Yes", no: "No" } as Record<string, string> },
    rent: { label: "Do you rent?", options: { yes: "Yes", no: "No" } as Record<string, string> },
    card: { label: "Do you have a concession card?", options: { yes: "Yes", no: "No", unsure: "Not sure" } as Record<string, string> },
  },
  remember: "Remember my answers to tailor these pointers",
  rememberNote: "Off by default. If it's off, your answers are forgotten when you leave this page.",
  see: "See pointers",
  resultsTitle: "Places to check",
  programs: {
    payment_finder: { title: "Government payments", body: "Services Australia's Payment and Service Finder shows what you might be able to get." },
    rent_assistance: { title: "Rent Assistance", body: "If you rent and get a government payment, you might also get help with rent." },
    concession_cards: { title: "Concession cards", body: "A concession card can lower costs like medicines and some bills." },
    state_concessions: { title: "State concessions and rebates", body: "Your state government lists energy, water and transport concessions." },
    nils: { title: "No-interest loans (NILS)", body: "Small loans with no interest or fees for essentials. An alternative to pay advances." },
    energy_compare: { title: "Compare energy plans", body: "The government's comparison site for energy plans." },
  } as Record<string, { title: string; body: string }>,
  open: (title: string) => `Open ${title} (official site)`,
  done: "Done",
};
