// Spec 08 "Ask Tippla" copy. Lead with the conclusion, then the evidence; estimates say so; never advice
// about credit products; distress leads with support; gambling is supportive, never judgemental.
export const assistantCopy = {
  title: "Ask Tippla",
  sub: "Questions about your money, answered from your own figures",
  entry: "Ask Tippla",
  entryBody: "Ask about your bills, spending, safe to spend or SmartScore.",
  askAbout: "Ask about this",
  placeholder: "For example: can I afford $80 on Saturday?",
  label: "Your question",
  send: "Ask",
  thinking: "Working it out",
  suggested: "You could ask",
  you: "You",
  tippla: "Tippla",
  helpful: "Was this helpful?",
  yes: "Yes",
  no: "No",
  thanks: "Thanks for letting us know",
  general: "General information from your own figures, not financial advice. Figures marked as estimates can change.",
  error: "Something went wrong. Try again, or see Help.",
  sample: "Sample logic · Q40",
  mode: { scripted: "Answers built from your figures", claude: "Answers written by an AI model from your figures" } as Record<string, string>,
  answers: {
    affordShortAlready: (amt: string, short: string, payday: string, after: string) =>
      `Probably not without running short. You're forecast to be about ${short} short before payday on ${payday}, and ${amt} would make that about ${after}. Here are some options.`,
    affordWouldShort: (amt: string, payday: string, after: string) =>
      `Probably not without running short. After your bills, ${amt} would leave you about ${after} short before payday on ${payday}.`,
    affordOk: (amt: string, payday: string, left: string) =>
      `It looks OK. After your bills and ${amt}, you'd have about ${left} left before payday on ${payday}. That's an estimate.`,
    affordAfterPayday: (date: string, payday: string) =>
      `${date} is after your payday on ${payday}, so it depends on what comes in. Your payday check-in will show safe to spend for the new pay cycle.`,
    safe: (amt: string, payday: string, days: number) => `About ${amt} a day for the ${days} days until payday on ${payday}. That's an estimate.`,
    safeNone: (payday: string) => `Nothing spare before payday on ${payday} once your bills are paid. If money's tight, there are options.`,
    forecastShort: (short: string, payday: string) => `You're forecast to be about ${short} short before payday on ${payday}. That's an estimate from your balance and the bills due.`,
    forecastOk: (left: string, payday: string) => `You're forecast to have about ${left} left after bills before payday on ${payday}. That's an estimate.`,
    billsNext: (merchant: string, amt: string, date: string) => `Your next bill is ${merchant}, about ${amt} on ${date}.`,
    billsBefore: (amt: string) => `Bills due before payday add up to about ${amt}.`,
    billsNone: "We don't see any bills due in the next two weeks.",
    subs: (n: number, year: string) => `You have ${n} subscriptions, about ${year} a year:`,
    subsNone: "We haven't found any regular subscriptions.",
    spending: (amt: string, cat: string, range: string, n: number) => `You've spent ${amt} on ${cat} from ${range}, across ${n === 1 ? "1 payment" : `${n} payments`}.`,
    spendingWhich: "Which kind of spending? For example takeaway, groceries, transport or shopping.",
    spendingHidden: "You've turned off gambling insights, so we don't show that here. You can turn them back on in Account › Profile.",
    score: (score: number, stage: string) => `Your SmartScore is ${score}, in the ${stage} stage.`,
    scoreChange: (delta: number, since: string) => (delta === 0 ? `It's steady since ${since}.` : `It's ${delta > 0 ? "up" : "down"} ${Math.abs(delta)} since ${since}.`),
    scoreParts: (parts: string) => `What moved it (estimated): ${parts}.`,
    scoreNext: (pts: number, stage: string) => `${pts} points to ${stage}.`,
    scoreNone: (why: string) => `There's no SmartScore yet: ${why}.`,
    plan: (title: string, step: string, label: string | null) => `Your plan: ${title}, step ${step}${label ? `: ${label}` : ""}.`,
    planNone: "You don't have a plan yet. Your plan page suggests one.",
    hardship: "If money's tight, these are real options, and using them doesn't count against your SmartScore:",
    hardshipList: (ndh: string) => [`Hardship support in Tippla: ask your lender for a hardship arrangement, with a letter we pre-fill.`, `Free financial counselling: the National Debt Helpline, ${ndh}.`, "No-interest loans (NILS) for essentials, instead of a pay advance.", "Pause or downgrade Tippla."],
    credit: "I can't recommend loans, lenders or whether to borrow. That's a decision for you, and a lender has to check it's suitable. Here's what I can see from your own figures:",
    creditAdvance: (provider: string, fee: string) => `Your ${provider} advances cost about ${fee} each in fees.`,
    creditShort: (short: string, payday: string) => `You're forecast to be about ${short} short before payday on ${payday}.`,
    creditAlt: "If money's tight, a no-interest loan (NILS), a hardship arrangement with a lender you already have, or a free financial counsellor are options worth a look. Your Borrowing page shows your loans if you want to explore yourself.",
    distress: "It sounds like things are really hard right now. You don't have to sort this out alone.",
    distressNdh: (ndh: string, hours: string) => `A free, confidential financial counsellor at the National Debt Helpline can help: ${ndh} (${hours}).`,
    distressCrisis: (phone: string) => `If you're feeling unsafe or overwhelmed, Lifeline is there any time on ${phone}.`,
    distressHardship: "Tippla's Hardship support page has options you can use straight away.",
    gambling: "If you'd like to spend less on gambling, there are free, confidential tools and people who can help, whenever you're ready.",
    gamblingLink: "Gambling support options are on the Hardship support page.",
    other: "I can help with your bills, spending, safe to spend, forecast, SmartScore and plan. For example:",
  },
  links: {
    hardship: "Options if money's tight",
    ndh: "Call the National Debt Helpline",
    lifeline: "Call Lifeline",
    borrowing: "Your Borrowing page",
    nils: "No-interest loans (official site)",
    gambling: "Gambling support options",
  },
  suggestions: {
    afford: "Can I afford $50 on Saturday?",
    score: "Why did my score change?",
    bills: "When's my next bill?",
    takeaway: "How much do I spend on takeaway?",
    subscriptions: "What subscriptions do I have?",
    safe: "How much can I spend each day?",
    plan: "What's my plan this pay cycle?",
  },
};
