// Spec 05 copy: corrections, forecast accuracy and bank connection health. Plain, no blame, never alarming.
export const correctionCopy = {
  notRight: "Not right?",
  notRightFor: (what: string) => `Not right? ${what}`,
  updated: "Got it. Your forecast is updated",
  scoreNote: "Your SmartScore is worked out by TaleFin, so it may take until the next refresh to reflect this.",
  undo: "Undo",
  bill: {
    title: (merchant: string) => `${merchant}: what's changed?`,
    intro: "Tell us and we'll fix your forecast and safe to spend straight away.",
    paid: "Already paid",
    amount: "Different amount",
    amountLabel: "New amount ($)",
    moved: "Moved to another day",
    movedLabel: "New date",
    notBill: "Not a bill",
    ended: "This has ended",
    save: "Save",
    invalidAmount: "Enter an amount between $1 and $20,000",
    invalidDate: "Pick a date after today",
  },
  subscription: {
    title: (merchant: string) => `${merchant}: what's not right?`,
    notSub: "Not a subscription",
    ended: "This has ended",
    endedNote: "We'll stop expecting it. If it's charged again, we'll show it as new.",
  },
  loan: {
    title: (provider: string) => `${provider}: what's not right?`,
    notLoan: "This isn't a loan",
    notLoanNote: "We'll treat its payments as a bill.",
    ended: "This has ended",
    endedNote: "We'll stop expecting repayments.",
  },
  transaction: {
    allFrom: (merchant: string) => `Do this for every ${merchant} payment, including future ones`,
    income: "What kind of money is this?",
    oneOff: "One-off",
    regular: "Regular pay",
    incomeNote: "One-off money is left out of your monthly income and your pay forecast.",
  },
  page: {
    title: "Your corrections",
    intro: "What you've told Tippla. These apply to new transactions too. Remove any to go back to what we'd worked out.",
    empty: "Nothing yet. Wherever a figure doesn't look right, tap \"Not right?\" to fix it.",
    remove: (label: string) => `Remove: ${label}`,
    removeButton: "Remove",
    removed: "Removed. Your forecast is updated",
    link: "Your corrections",
    count: (n: number) => (n === 0 ? "Nothing corrected yet" : n === 1 ? "1 correction" : `${n} corrections`),
    kinds: {
      category: (m: string, c: string) => `${m}: always ${c}`,
      not_bill: (m: string) => `${m}: not a bill`,
      bill_ended: (m: string) => `${m}: bill has ended`,
      not_subscription: (m: string) => `${m}: not a subscription`,
      subscription_ended: (m: string) => `${m}: subscription has ended`,
      not_loan: (m: string) => `${m}: not a loan`,
      loan_ended: (m: string) => `${m}: loan has ended`,
      income_one_off: (m: string) => `${m}: one-off money`,
      income_regular: (m: string) => `${m}: regular pay`,
    },
    billPaid: (m: string, d: string) => `${m} due ${d}: already paid`,
    billAmount: (m: string, d: string, a: string) => `${m} due ${d}: ${a}`,
    billMoved: (m: string, d: string, to: string) => `${m} due ${d}: moved to ${to}`,
  },
};

export const accuracyCopy = {
  line: (within: string, hits: number, of: number) => `Our forecasts for you have been within ${within} on ${hits} of the last ${of} days.`,
  missTitle: (day: string) => `We got ${day} wrong`,
  missBody: (date: string, predicted: string, actual: string) => `For ${date} we expected about ${predicted} in your account. It ended the day at ${actual}.`,
  answers: {
    one_off: "A one-off cost",
    bill_moved: "A bill came out on a different day",
    pay_different: "My pay was different",
    nothing: "Nothing unusual",
  } as Record<string, string>,
  thanks: "Thanks. That helps us get your forecast right",
  fixBill: "Fix a bill",
};

export const healthCopy = {
  basedOn: (day: string) => `Based on data from ${day}`,
  reconnect: "Reconnect",
  paused: "Reconnect to see today's figure",
  pausedBody: (day: string) => `Your bank data is from ${day}, so we've paused safe to spend rather than guess.`,
  statusExpiring: (day: string) => `Your bank connection ends ${day} · Renew it to keep your forecast up to date`,
  feed: {
    expiringTitle: (n: number) => (n === 0 ? "Your bank connection ends today" : `Your bank connection ends in ${n} ${n === 1 ? "day" : "days"}`),
    expiringBody: (day: string) => `Renew by ${day} so your forecast and safe to spend keep updating. It takes about a minute.`,
    renew: "Renew connection",
    staleTitle: "We haven't had new bank data for a while",
    staleBody: (day: string) => `The latest is from ${day}. Reconnecting usually fixes it.`,
  },
  push: {
    title: (n: number) => (n === 0 ? "Your bank connection ends today" : `Your bank connection ends in ${n} days`),
    body: "Renew it in Tippla to keep your forecast up to date.",
  },
  bank: {
    status: { healthy: "Connected", stale: "Not updating", broken: "Needs reconnecting", expiring: "Ending soon" } as Record<string, string>,
    consentEnds: (day: string) => `Access ends ${day}`,
    renew: "Renew access",
    reminders: (days: string[]) => `We'll remind you on ${days.length === 1 ? days[0] : `${days.slice(0, -1).join(", ")} and ${days.at(-1)}`}.`,
    reconnect: "Reconnect",
    addTitle: "Add your other account?",
    addBody: (n: number) => `We've seen ${n === 1 ? "a transfer" : `${n} transfers`} to an account in your name that isn't connected. Connecting it keeps your forecast complete.`,
    add: "Add your other account",
  },
  flow: {
    title: "Reconnect your bank",
    intro: "You'll go to TaleFin to renew read-only access, then come straight back to where you were.",
    go: "Continue to TaleFin",
    done: "Reconnected. Your data is up to date",
  },
};
