export const dashboard = {
  hi: (name: string) => `Hi ${name}`,
  notifications: "Notifications",
  scoreHeader: (score: number, stage: string) => `SmartScore ${score} · ${stage}`,
  scoreRange: (a: number, b: number) => `${a}–${b}`,
  points: (n: number) => `${n} points`,
  toStage: (s: string, at: number) => `to ${s} at ${at}`,
  topStage: "You're in the top stage",
  seeShaping: "See what's shaping it",
  thinHeader: "SmartScore",
  thinBody: "Not enough history yet",
  nextThing: "Next thing to do",
  seeHow: "See how",
  nextBill: (day: string) => `Next bill · ${day}`,
  predicted: "predicted",
  spending: "Spending",
  sixMonths: "6 months",
  range: (from: string, to: string, partial: string | null) => `${from}–${to}${partial ? ` · ${partial}` : ""}`,
  partial: (m: string, day: string) => `${m} to ${day}`,
  tapMonth: "Tap a month to explore spending",
  monthBar: (m: string, amt: string, partial: boolean) => `${m}: ${amt}${partial ? " so far" : ""}. Open spending for this month`,
  noData: "No data",
  dueTitle: "What's due before payday",
  dueTotal: (amt: string) => `${amt} due before payday`,
  dueRounding: (exact: string) => `Exact total ${exact}; amounts above are rounded.`,
  openCalendar: "Open calendar",
  dueEmpty: "Nothing else is due before payday.",
  incomeIn: "Paid in",
  comingIn: "Coming in next",
  incomeRow: (payer: string, amt: string, day: string) => `${payer} ${amt} · ${day}`,
  incomeRowAbout: (payer: string, amt: string, day: string) => `${payer} about ${amt} · ${day}`,
  advanceTitle: "Pay advance",
  advanceBody: (provider: string, amt: string, fee: string, repay: string, date: string) =>
    `${provider} advanced ${amt} on this pay cycle. The fee is ${fee}, so ${repay} comes out on ${date}. A pay advance isn't income: it's borrowing against your next pay.`,
  banners: {
    hardship: "Money tight right now? There are options",
    newOffer: (n: number) => (n === 1 ? "You have 1 new offer" : `You have ${n} new offers`),
    scoreDrop: (n: number) => `Your SmartScore dropped ${n} points. See what changed`,
    bankDisconnected: "You've disconnected your bank, so your numbers have stopped updating. Reconnect any time.",
    bankExpired: (d: string) => `Your bank connection has expired, so your numbers stopped updating on ${d}. Reconnect to refresh them.`,
  },
};
