// Onboarding copy (O1–O5). Consent wording follows docs/04 and Astra's consent fixture.
export const onboarding = {
  shell: { back: "Back", support: "Support", hardship: "Hardship support", stepOf: (n: number, total: number) => `Step ${n} of ${total}` },
  createAccount: {
    title: "Let's get you set up",
    intro: "See what's shaping your SmartScore and what would change a lender's answer.",
    email: "Email",
    emailHelp: "We'll send account updates here.",
    mobile: "Mobile",
    mobileHelp: "For example 0412 345 678.",
    continue: "Continue",
    errors: {
      email: "Enter an email address like name@example.com",
      mobile: "That mobile number needs 10 digits, starting with 04",
    },
  },
  password: {
    title: "Secure your account",
    intro: "Use a password, or a passkey if your phone supports it.",
    password: "Create a password",
    passwordHelp: "At least 10 characters.",
    show: "Show password",
    hide: "Hide password",
    continue: "Continue",
    passkey: "Use a passkey instead",
    passkeyTitle: "Passkeys",
    passkeyBody: "In the full product, your phone creates a passkey so you can sign in with your face, fingerprint or PIN. In this demo it continues without one.",
    passkeyContinue: "Continue with a passkey",
    error: "Use at least 10 characters",
  },
  consents: {
    title: "Your choices",
    intro: "Choose what you share with Tippla.",
    required: "Required",
    optional: "Optional.",
    whatThisMeans: "What this means",
    continue: "Continue",
    tickBoth: "Tick both required boxes to continue.",
    saving: "Saving your choices…",
    items: {
      ff_data_sharing: {
        title: "Share my Friendly Finance application with Tippla",
        explanation: "Tippla receives the details you gave Friendly Finance in your application.",
        detail: "This shares your completed Friendly Finance application with Tippla. This permission is needed to continue.",
      },
      talefin_bank_data: {
        title: "Let Tippla read my bank data through TaleFin",
        explanation: "TaleFin gives Tippla access to read your connected bank data.",
        detail: "This lets Tippla read bank data through TaleFin for your SmartScore and spending view. This permission is needed to continue.",
      },
      lender_matching: {
        title: "Let Tippla show my profile to partner lenders when I might qualify",
        explanation: "Tippla works fully without this. You can turn it on or off any time.",
        detail: "If you choose this, Tippla can show your profile to partner lenders when you might qualify. Leave it unticked to use Tippla without lender matching.",
      },
    },
  },
  connect: {
    title: "Connect your bank",
    intro: "Tippla uses TaleFin to read your bank data. Here's what happens.",
    points: [
      "You'll leave Tippla briefly to log in to your bank through TaleFin.",
      "It's read-only: nobody can move money or make payments.",
      "It takes about two minutes.",
      "You can disconnect any time in Account → Bank connections.",
    ],
    button: "Connect with TaleFin",
    returning: "Returning you to Tippla",
    connected: (bank: string, account: string, last4: string) => `Connected to ${bank} · ${account} ••${last4}`,
    otherTitle: "Any other accounts?",
    otherBody: "Do you use any other accounts, like savings or another bank? Connecting them keeps money you move between your own accounts out of your spending.",
    addAnother: "Add another account",
    thatsAll: "That's all of them",
    addAnotherSheetTitle: "Add another account",
    addAnotherSheetBody: "In the full product this opens TaleFin again so you can connect another account. In this demo only one account is connected.",
    addAnotherOk: "Back to my accounts",
  },
  talefin: {
    badge: "TaleFin",
    note: "Demo screen. This stands in for TaleFin's secure bank login; nothing is sent anywhere.",
    title: "Choose your bank",
    loginTitle: (bank: string) => `Log in to ${bank}`,
    clientNumber: "Client number",
    password: "Password",
    login: "Log in and share",
    readOnly: "Read-only access for Tippla. TaleFin can't move money.",
    cancel: "Cancel and return to Tippla",
  },
  analysing: {
    title: "Working out your SmartScore",
    intro: "This usually takes under a minute.",
    steps: ["Reading 6 months of transactions", "Finding your pay cycle", "Checking loans and repayments", "Working out your SmartScore"],
    done: "Done",
    inProgress: "In progress",
    waiting: "Waiting",
    finished: "All done. Opening your SmartScore.",
    continue: "See my SmartScore",
  },
  reveal: {
    headline: (score: number) => `Your SmartScore is ${score}.`,
    line: (stage: string) => `That puts you in the ${stage} stage. Here's what's shaping it, and the first thing that would move it.`,
    biggestFactor: "Biggest factor with room to move",
    firstThing: "First thing to do",
    seeHow: "See how",
    dashboard: "See your dashboard",
    thinTitle: "Not enough history yet",
    canSee: "What we can already see",
    payCycle: "Pay cycle",
    pay: "Pay",
    payAmount: (amt: string) => `About ${amt}`,
    payEvery: (weekday: string) => `Every second ${weekday}`,
    history: "History so far",
    historyDays: (n: number) => `${n} days`,
    loansOpen: (n: number) => `You have ${n} loans open.`,
    measures: "What it measures",
    driving: "What's driving it",
    lifts: "What lifts it",
  },
} as const;
