// Phase 4 copy: Spending (Overview · Categories · Budgets), comparison, calendar, subscriptions (en-AU).
// Numbers come from selectors; these functions only word them.
import { formatMonthLong } from "@/lib/format/dates";

export const monthLabel = (month: string) => `${formatMonthLong(month)} ${month.slice(0, 4)}`;

export const spending = {
  /** Spending v5 (09/10/2026): one column, sections, the B2 category panel. */
  v5: {
    askPlaceholder: "Ask Tippla about your spending",
    periodLabel: "Period",
    cycleMeta: (from: string, to: string, payday: string) => `${from} – ${to} · payday ${payday}`,
    periodMeta: (from: string, to: string) => `${from} – ${to}`,
    sectionsLabel: "Sections",
    sections: {
      cycle: { chip: "This cycle", title: "This cycle so far", desc: "Where your money went since payday", titlePeriod: "This period", descPeriod: "Where your money went" },
      plan: { chip: "Plan ahead", title: "Plan ahead", desc: "Small changes for next cycle" },
      lenders: { chip: "Lenders", title: "Longer term", desc: "How this looks when you borrow" },
      activity: { chip: "Activity", title: "Activity", desc: (n: number) => (n === 1 ? "1 transaction" : `${n} transactions`) },
    },
    short: (amt: string) => `${amt} short`,
    shortRest: " before payday",
    seeComingUp: "See Coming up",
    summary: {
      heading: "This pay cycle",
      headingPeriod: (label: string) => label,
      compare: "Compare cycles",
      spentByDay: (day: number, of: number) => `spent by day ${day} of ${of}`,
      spentPeriod: "spent",
      everyday: "Everyday spending",
      more: (amt: string) => `${amt} more on everyday spending than at this point last cycle`,
      less: (amt: string) => `${amt} less on everyday spending than at this point last cycle`,
      morePeriod: (amt: string) => `${amt} more on everyday spending than the period before`,
      lessPeriod: (amt: string) => `${amt} less on everyday spending than the period before`,
      same: "Everyday spending is about the same as at this point last cycle",
      usual: (amt: string, n: number) => `Your full cycle is usually about ${amt}${n < 3 ? ` (based on ${n === 1 ? "1 cycle" : `${n} cycles`})` : ""}`,
      plusPending: (amt: string) => `plus ${amt} pending`,
      paidIn: "Paid in",
      payAdvance: "Pay advance",
      payAdvanceNote: "not income",
      pending: "Pending",
    },
    where: {
      heading: "Where it went",
      count: (n: number) => (n === 1 ? "1 category" : `${n} categories`),
      fixed: "Fixed costs",
      repayments: "Repayments",
      same: "same",
      colEveryday: "Everyday",
      colThis: "This cycle",
      colThisPeriod: "This period",
      colVs: "vs last",
      groups: { essential: "Essentials", lifestyle: "Lifestyle" },
      changeSr: (amt: string, up: boolean) => `${up ? "up" : "down"} ${amt} on this point last cycle`,
      sameSr: "same as this point last cycle",
      tiles: { spent: "Spent so far", spentPeriod: "Spent", usualByDay: (n: number) => `Usual by day ${n}`, usualFull: "Usual full cycle" },
      status: {
        over_cycle: (amt: string) => `${amt} over your usual cycle`,
        ahead: (amt: string) => `${amt} more than usual by now`,
        about: "About usual for this point",
      },
      detailChange: (up: boolean, amt: string) => `${up ? "Up" : "Down"} ${amt} on this point last cycle.`,
      detailMostly: (merchant: string, amt: string) => `Mostly ${merchant} (${amt}).`,
      merchantsLabel: (name: string) => `${name}: merchants`,
      txCount: (n: number) => (n === 1 ? "1 transaction" : `${n} transactions`),
      pending: "Pending",
      setBudget: (amt: string) => `Set a budget of ${amt}`,
      editBudget: (amt: string) => `Budget: ${amt}`,
      wrongCategory: "Wrong category?",
      seeAll: (n: number) => `See all ${n}`,
      noUsual: "Not enough history for a usual amount yet.",
    },
    budgets: {
      heading: "Budget ideas",
      all: "All budgets",
      intro: "Based on your last three pay cycles. Tap an amount to change it.",
      usually: (amt: string) => `usually ${amt}`,
      try: "Try", aCycle: "a cycle",
      setPill: (amt: string) => `Set ${amt}`,
      setSuffix: (name: string) => `budget for ${name}`,
      notNowSr: (name: string) => `Not now for ${name}`,
      changeSr: (name: string, amt: string) => `Change the ${name} amount, now ${amt}`,
      amountLabel: (name: string) => `${name} budget a cycle, in dollars`,
      invalid: "Enter a whole dollar amount.",
      done: (amt: string) => `Budget set: ${amt} a cycle`,
      undo: "Undo",
      undoSuffix: (name: string) => `the ${name} budget`,
    },
    lenders: {
      heading: "How lenders see your spending",
      details: "Details",
      detailsSr: ": your loans and credit",
      body: "When you apply for credit, lenders read your bank statements. These are the things they tend to look at this cycle.",
      loans: "Loan repayments", payAdvances: "Pay advances", gambling: "Gambling",
      lendersN: (n: number) => (n === 1 ? "1 lender" : `${n} lenders`),
      advancesN: (n: number) => `${n} this cycle`,
      depositsN: (n: number) => (n === 1 ? "1 deposit" : `${n} deposits`),
      scoreLine: "See how this affects your SmartScore",
      seeHow: "See how",
      gamblingSr: ": how gambling affects your SmartScore",
    },
    activity: {
      double: (merchant: string, amt: string) => `${merchant} may have charged you twice (${amt})`,
      review: "Review",
      seeAll: (n: number) => `See all ${n} transactions`,
    },
    housekeeping: { heading: "Something in the wrong category?", body: "Tap any transaction to move it.", fix: "Fix" },
  },
  title: "Spending",
  search: "Search transactions",
  tabs: { overview: "Overview", categories: "Categories", budgets: "Budgets" },
  tabsLabel: "Spending views",
  periodsLabel: "Period",
  limitedHistory: (days: number) => `Based on ${days} days. That's all the history we have so far.`,
  partialMonth: (to: string) => `Month to ${to}`,
  hero: {
    total: (amt: string) => `${amt} spent`,
    paidIn: (amt: string) => `${amt} paid in`,
    perCycle: (amt: string) => `About ${amt} a pay cycle`,
    switchHint: "Switch to This pay cycle to see what's left before payday.",
    seeDue: "See what's due",
    shortBy: "Short",
    leftOver: "Left",
  },
  insightsContext: "Your spending",
  insights: {
    food: (merchant: string, amt: string, n: number) => ({
      title: `${amt} on ${merchant} this pay cycle`,
      summary: `${n} ${n === 1 ? "order" : "orders"} so far this pay cycle.`,
      happening: (cat: string, catAmt: string) =>
        `You've spent ${catAmt} on ${cat} this pay cycle. ${merchant} makes up ${amt} of that, across ${n} ${n === 1 ? "order" : "orders"}.`,
      wouldChange: "If you want a limit to aim for, a budget shows how much is left each pay cycle.",
    }),
    /** when: "in May 2026", "last pay cycle", "over the last 3 months". */
    foodPeriod: (merchant: string, amt: string, n: number, when: string) => ({
      title: `${amt} on ${merchant} ${when}`,
      summary: `${n} ${n === 1 ? "order" : "orders"} in this period.`,
    }),
    subscriptions: (n: number, perCycle: string, perYear: string) => ({
      title: `${n} regular ${n === 1 ? "subscription" : "subscriptions"}`,
      summary: `About ${perCycle} a pay cycle, ${perYear} a year.`,
      happening: `${n} regular ${n === 1 ? "subscription comes" : "subscriptions come"} out of your account, about ${perCycle} a pay cycle. If you use them all, there's nothing to do here.`,
      wouldChange: `${perYear} a year, all together.`,
    }),
    setBudget: (cat: string) => `Set a ${cat.toLowerCase()} budget`,
    adjustBudget: (cat: string) => `Adjust my ${cat.toLowerCase()} budget`,
    reviewSubscriptions: "Review subscriptions",
    scoreMethod: "See how your score is worked out",
    support: "View support options",
    notNow: "Not now",
  },
  /** 08/10/2026: the ranked list that replaced the donut on Overview. */
  breakdown: {
    heading: "Spending by category",
    lead: (total: string, period: string) => `${total} spent · ${period}`,
    biggest: (name: string, amt: string, pct: string) => `Most went on ${name}: ${amt}, ${pct} of your spending.`,
    shareSr: (pct: string) => `${pct} of spending`,
    up: (amt: string, vs: string) => `Up ${amt} vs ${vs}`,
    down: (amt: string, vs: string) => `Down ${amt} vs ${vs}`,
    same: (vs: string) => `Same as ${vs}`,
    showMore: (n: number) => `Show ${n} more`,
    showFewer: "Show fewer",
    seeAll: (n: number) => `See all ${n}`,
    seeAllSr: (name: string) => ` ${name} transactions`,
    lenders: "Lenders look at this",
    lendersSr: (name: string) => `: ${name}, and how it affects your SmartScore`,
    noTransactions: "No transactions in this period.",
    empty: "No spending this period",
    pending: "Pending",
  },
  categories: {
    seeAll: (n: number) => `See all ${n} categories`,
    heading: "Categories",
    count: (n: number) => `${n} shown`,
    filterLabel: "Type",
    filters: { all: "All", essentials: "Essentials", lifestyle: "Lifestyle" },
    sortLabel: "Sort by",
    sorts: { amount: "Amount", change: "Change vs last period", az: "A–Z" },
    accountLabel: "Account",
    allAccounts: "All accounts",
    change: (amt: string, up: boolean, vs: string) => `${up ? "Up" : "Down"} ${amt} vs ${vs}`,
    noChange: (vs: string) => `Same as ${vs}`,
    sparkline: (name: string) => `${name}, last 6 pay cycles`,
    empty: "Nothing in this view. Try All.",
    clearFilter: "Clear filter",
  },
  when: { last_cycle: "last pay cycle", month: (label: string) => `in ${label}`, rolling: (label: string) => `over the last ${label}` },
  vsLabel: { this_cycle: "last pay cycle", last_cycle: "the pay cycle before", month: "the month before", rolling: "the period before" },
  filters: {
    label: "Filtered by",
    search: (q: string) => `"${q}"`,
    clearAll: "Clear all",
  },
  feed: {
    heading: "Transactions",
    count: (n: number) => (n === 1 ? "1 transaction" : `${n} transactions`),
    searchLabel: "Search merchant or amount",
    showMore: (n: number) => `Show ${n} more`,
    direction: { all: "All", out: "Money out", in: "Money in" },
    directionLabel: "Direction",
    filteredTo: (name: string) => `Showing ${name}`,
  },
  tx: {
    category: "Category",
    pending: "Pending. Not counted in totals until it clears.",
    allFrom: (m: string) => `All ${m} transactions`,
    moved: (cat: string) => `Moved to ${cat}. Totals updated`,
    // The change-category drawer (buttons brief, 09/10/2026).
    alsoAll: (m: string, cat: string) => `Also move all ${m} payments to ${cat}, including future ones`,
    movedTo: (cat: string) => `Moved to ${cat}`,
    movedToAll: (cat: string, m: string) => `Moved to ${cat}, including future ${m} payments`,
    undo: "Undo",
    undoSr: "the category change",
    ruleExists: (m: string, cat: string) => `All ${m} payments go to ${cat}`,
    change: "Change",
    changeSr: (m: string) => `the category for all ${m} payments`,
    reset: "Back to the original category",
    original: (cat: string) => `Originally ${cat}`,
    transferNote: "Transfers between your accounts don't count as spending.",
    hint: "Wrong category? Change it here and every total updates.",
  },
  merchant: {
    lead: (n: number, amt: string, period: string) => `${n} ${n === 1 ? "transaction" : "transactions"} · ${amt} · ${period}`,
    categoryFor: (m: string, date: string) => `Category for ${m} on ${date}`,
  },
  budgets: {
    pageTitle: "All budgets",
    heading: "Budgets this pay cycle",
    intro: "Budgets are per pay cycle. Set one for any category you want to keep an eye on.",
    summary: (spent: string, budget: string) => `${spent} spent of ${budget} budgeted`,
    summaryNote: (n: number) => (n === 1 ? "Across 1 budgeted category" : `Across ${n} budgeted categories`),
    none: "No budgets yet. Set one on any category below.",
    suggestIntro: "Some ideas from your last three pay cycles. Set one, change the amount, or skip it.",
    suggest: (avg: string, amt: string) => `you average ${avg} a pay cycle. Set a ${amt} budget?`,
    set: "Set",
    setSr: (amt: string, name: string) => `Set a ${amt} budget for ${name}`,
    adjust: "Adjust",
    dismiss: "Dismiss",
    noBudget: "No budget",
    editTitle: (cat: string) => `${cat} budget`,
    amountLabel: "Budget per pay cycle",
    amountHint: (avg: string) => `You've averaged ${avg} a pay cycle over the last 3 pay cycles.`,
    amountHintNone: "No spending in this category over the last 3 pay cycles.",
    save: "Save budget",
    remove: "Remove budget",
    saved: (cat: string) => `${cat} budget saved`,
    removed: (cat: string) => `${cat} budget removed`,
    invalid: "Enter an amount of $0 or more, like 200",
    otherCategories: "Other categories",
  },
  compareLink: "Compare with past pay cycles",
  calendarLink: "Open calendar",
  subscriptionsLink: "Subscriptions",
} as const;

export const compare = {
  title: "Spending comparison",
  intro: "Context for your spending, not a league table.",
  tabsLabel: "Compare with",
  tabs: { history: "Your last 3 pay cycles", cohort: "People in a similar situation" },
  history: {
    note: (days: number) => `This pay cycle so far covers ${days} of 14 days.`,
    thisCycle: "This pay cycle so far",
    average: "Average of last 3",
    cycles: "Last 3 pay cycles",
    cycleLabel: (start: string) => `From ${start}`,
    notEnough: "We need at least one full pay cycle of history to compare.",
  },
  cohort: {
    intro: "How your spending compares with people in a similar situation (age, income, region).",
    incomeBand: (from: string, to: string) => `${from}–${to} a month`,
    who: (age: string, income: string, region: string) => `People aged ${age}, earning ${income}, in ${region}.`,
    you: "You",
    typical: "Typical range",
    middle: "Middle",
    perCycle: "Per pay cycle, your average over the last 3 pay cycles.",
    excluded: "Gambling, alcohol and borrowing aren't compared.",
    sample: "Sample cohort data",
    row: (name: string, you: string, low: string, high: string, mid: string) =>
      `${name}: you ${you}. Typical range ${low} to ${high}, middle ${mid}.`,
    notEnough: "We need at least one full pay cycle of history to compare.",
  },
} as const;

export const calendarPage = {
  // Month first (09/10/2026; reference: tippla-calendar-mockup.dc.html).
  title: "Calendar",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  updated: (when: string) => `Updated ${when}`,
  stale: (when: string) => `Last updated ${when}. Your bank hasn't sent new data for over a day, so these figures may be out of date.`,
  reconnect: "Check your bank connection",
  banner: {
    title: (amt: string, day: string) => `You're forecast to be ${amt} short on ${day}`,
    body: (bills: string, perDay: string) => `That's after ${bills} of bills still to come, but before everyday spending. You've averaged about ${perDay} a day on that this month.`,
    options: "Options if money's tight",
  },
  stats: {
    label: "Your money now",
    today: "Balance today",
    lowest: "Lowest forecast",
    lowestNone: "No forecast yet",
    dayBeforePayday: "day before payday",
    bills: "Bills still to come",
    billsNone: "None before payday",
    below: "Days below $0",
    belowOf: (n: number) => `of ${n} so far this month`,
  },
  grid: {
    label: (month: string) => `${month}. Each day shows its end-of-day balance.`,
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    today: "Today",
    forecast: "Forecast",
    lowest: "Lowest",
    more: (n: number) => `+${n} more`,
    out: (amt: string) => `Out ${amt}`,
    noBalance: "—",
    forecastEnds: (day: string) => `From ${day} there's no forecast yet. We forecast to the end of your next pay cycle.`,
    pay: (amt: string) => `Pay ${amt}`,
    dayLabel: (day: string, forecast: boolean, balance: string | null, extra: string[]) =>
      [`${day}, ${balance === null ? "no balance" : `${forecast ? "forecast balance" : "end-of-day balance"} ${balance}`}`, ...extra].join(", "),
  },
  quick: { label: "Show", today: "Today", lastCycle: "Last pay cycle", thisCycle: "This pay cycle", month: "Whole month" },
  range: { hint: "Drag across days or Shift-click to pick a range", start: "Select range", pickStart: "Tap a start date", pickEnd: "Now tap an end date" },
  legend: {
    pay: "Pay", payNote: "Money in",
    bill: "Bill", billNote: "Bills, rent & repayments",
    advance: "Beforepay", advanceNote: "Pay advances",
    below: "Below $0", forecast: "Forecast",
    bold: "Bold figure = end-of-day balance",
  },
  panel: {
    label: "Selected days",
    today: "Today",
    days: (n: number) => `${n} days`,
    includesForecast: (day: string) => `Includes forecast from ${day}`,
    pending: (amt: string) => `${amt} pending, not yet in balance`,
    opening: "Opening balance",
    moneyIn: "Money in",
    moneyOut: "Money out",
    closing: "Closing balance",
    closingForecast: "Forecast closing",
    lowest: "Lowest point",
    chart: "End-of-day balance",
    chartSr: (from: string, to: string, low: string, lowDay: string) => `End-of-day balance from ${from} to ${to}. Lowest ${low} on ${lowDay}. Every figure is in the list below.`,
    endOfDay: (amt: string) => `End of day ${amt}`,
    forecastEndOfDay: (amt: string) => `Forecast end of day ${amt}`,
    noBalance: "No balance for this day",
    pendingTag: "Pending",
    predictedTag: "Predicted",
    none: "No transactions",
    noneForecast: "Nothing predicted. Everyday spending isn't forecast.",
  },
} as const;

export const subscriptionsPage = {
  title: "Subscriptions",
  intro: "Regular charges we've found in your account.",
  total: (perCycle: string, perYear: string) => `About ${perCycle} a pay cycle · ${perYear} a year`,
  count: (n: number) => (n === 1 ? "1 subscription" : `${n} subscriptions`),
  perCycleShort: "a pay cycle",
  perYearLine: (amt: string) => `${amt} a year`,
  perYearShort: (amt: string) => `${amt} a year`,
  railLabel: "Subscription totals",
  notUsingHeading: "You said you don't use",
  notUsingNone: "Answer \"Still using it?\" on a subscription and any you don't use show here, with what cancelling would save.",
  notUsingSaving: (amt: string) => `Cancelling these would save about ${amt} a year`,
  moreFor: (m: string) => `More options for ${m}`,
  changeAnswer: "Change my answer",
  cancelledState: "You've cancelled this. We'll check it doesn't charge again.",
  amount: (amt: string, cadence: string) => `${amt} ${cadence}`,
  cadence: { monthly: "a month" },
  lastCharged: (date: string) => `Last charged ${date}`,
  nextCharge: (date: string) => `Next expected ${date}`,
  perCycle: (amt: string) => `${amt} a pay cycle`,
  perYear: (amt: string) => `${amt} a year`,
  keep: "Keep",
  kept: "Kept",
  keptToast: (m: string) => `${m} marked as kept`,
  remind: "Remind me before next charge",
  reminderSet: (date: string) => `Reminder set for ${date}`,
  reminderToast: (m: string, date: string) => `We'll remind you about ${m} on ${date}`,
  cancelReminder: "Cancel reminder",
  howToCancel: "How to cancel",
  undo: "Undo",
  cancelTitle: (m: string) => `How to cancel ${m}`,
  cancelSteps: (m: string, next: string) => [
    `Sign in to ${m} on its website or app.`,
    "Go to your account, membership or billing settings.",
    "Choose cancel, and follow the steps until you see a confirmation.",
    `You'll usually keep access until the end of what you've paid for. The next charge is expected around ${next}.`,
  ],
  cancelStore: "If you signed up through Apple or Google, cancel it in your phone's subscription settings instead.",
  cancelAfter: "Tippla can't cancel it for you. Once it's cancelled, it drops off this list after its next expected date passes.",
  empty: "We haven't found any regular subscriptions.",
  emptyAction: "Review transactions",
} as const;
