// Phase 4 copy: Spending (Overview · Categories · Budgets), comparison, calendar, subscriptions (en-AU).
// Numbers come from selectors; these functions only word them.
import { formatMonthLong } from "@/lib/format/dates";

export const monthLabel = (month: string) => `${formatMonthLong(month)} ${month.slice(0, 4)}`;

export const spending = {
  title: "Spending",
  search: "Search transactions",
  tabs: { overview: "Overview", categories: "Categories", budgets: "Budgets" },
  tabsLabel: "Spending views",
  periodsLabel: "Period",
  limitedHistory: (days: number) => `Based on ${days} days. That's all the history we have so far.`,
  partialMonth: (to: string) => `Month to ${to}`,
  hero: {
    total: (amt: string) => `${amt} spent`,
    paidIn: (amt: string) => `${amt} paid in`,
    perCycle: (amt: string) => `About ${amt} a pay cycle`,
    switchHint: "Switch to This pay cycle to see what's left before payday.",
    seeDue: "See what's due",
    shortBy: "Short",
    leftOver: "Left",
  },
  insightsContext: "Your spending",
  insights: {
    food: (merchant: string, amt: string, n: number) => ({
      title: `${amt} on ${merchant} this pay cycle`,
      summary: `${n} ${n === 1 ? "order" : "orders"} so far this pay cycle.`,
      happening: (cat: string, catAmt: string) =>
        `You've spent ${catAmt} on ${cat} this pay cycle. ${merchant} makes up ${amt} of that, across ${n} ${n === 1 ? "order" : "orders"}.`,
      wouldChange: "If you want a limit to aim for, a budget shows how much is left each pay cycle.",
    }),
    /** when: "in May 2026", "last pay cycle", "over the last 3 months". */
    foodPeriod: (merchant: string, amt: string, n: number, when: string) => ({
      title: `${amt} on ${merchant} ${when}`,
      summary: `${n} ${n === 1 ? "order" : "orders"} in this period.`,
    }),
    subscriptions: (n: number, perCycle: string, perYear: string) => ({
      title: `${n} regular ${n === 1 ? "subscription" : "subscriptions"}`,
      summary: `About ${perCycle} a pay cycle, ${perYear} a year.`,
      happening: `${n} regular ${n === 1 ? "subscription comes" : "subscriptions come"} out of your account, about ${perCycle} a pay cycle. If you use them all, there's nothing to do here.`,
      wouldChange: `${perYear} a year, all together.`,
    }),
    setBudget: (cat: string) => `Set a ${cat.toLowerCase()} budget`,
    adjustBudget: (cat: string) => `Adjust my ${cat.toLowerCase()} budget`,
    reviewSubscriptions: "Review subscriptions",
    scoreMethod: "See how your score is worked out",
    support: "View support options",
    notNow: "Not now",
  },
  /** 08/10/2026: the ranked list that replaced the donut on Overview. */
  breakdown: {
    heading: "Spending by category",
    lead: (total: string, period: string) => `${total} spent · ${period}`,
    biggest: (name: string, amt: string, pct: string) => `Most went on ${name}: ${amt}, ${pct} of your spending.`,
    shareSr: (pct: string) => `${pct} of spending`,
    up: (amt: string, vs: string) => `Up ${amt} vs ${vs}`,
    down: (amt: string, vs: string) => `Down ${amt} vs ${vs}`,
    same: (vs: string) => `Same as ${vs}`,
    showMore: (n: number) => `Show ${n} more`,
    showFewer: "Show fewer",
    seeAll: (n: number) => `See all ${n}`,
    seeAllSr: (name: string) => ` ${name} transactions`,
    lenders: "Lenders look at this",
    lendersSr: (name: string) => `: ${name}, and how it affects your SmartScore`,
    noTransactions: "No transactions in this period.",
    empty: "No spending this period",
    pending: "Pending",
  },
  categories: {
    seeAll: (n: number) => `See all ${n} categories`,
    heading: "Categories",
    count: (n: number) => `${n} shown`,
    filterLabel: "Type",
    filters: { all: "All", essentials: "Essentials", lifestyle: "Lifestyle" },
    sortLabel: "Sort by",
    sorts: { amount: "Amount", change: "Change vs last period", az: "A–Z" },
    accountLabel: "Account",
    allAccounts: "All accounts",
    change: (amt: string, up: boolean, vs: string) => `${up ? "Up" : "Down"} ${amt} vs ${vs}`,
    noChange: (vs: string) => `Same as ${vs}`,
    sparkline: (name: string) => `${name}, last 6 pay cycles`,
    empty: "Nothing in this view. Try All.",
    clearFilter: "Clear filter",
  },
  when: { last_cycle: "last pay cycle", month: (label: string) => `in ${label}`, rolling: (label: string) => `over the last ${label}` },
  vsLabel: { this_cycle: "last pay cycle", last_cycle: "the pay cycle before", month: "the month before", rolling: "the period before" },
  filters: {
    label: "Filtered by",
    search: (q: string) => `"${q}"`,
    clearAll: "Clear all",
  },
  feed: {
    heading: "Transactions",
    count: (n: number) => (n === 1 ? "1 transaction" : `${n} transactions`),
    searchLabel: "Search merchant or amount",
    showMore: (n: number) => `Show ${n} more`,
    direction: { all: "All", out: "Money out", in: "Money in" },
    directionLabel: "Direction",
    filteredTo: (name: string) => `Showing ${name}`,
  },
  tx: {
    category: "Category",
    pending: "Pending. Not counted in totals until it clears.",
    allFrom: (m: string) => `All ${m} transactions`,
    moved: (cat: string) => `Moved to ${cat}. Totals updated`,
    reset: "Back to the original category",
    original: (cat: string) => `Originally ${cat}`,
    transferNote: "Transfers between your accounts don't count as spending.",
    hint: "Wrong category? Change it here and every total updates.",
  },
  merchant: {
    lead: (n: number, amt: string, period: string) => `${n} ${n === 1 ? "transaction" : "transactions"} · ${amt} · ${period}`,
    categoryFor: (m: string, date: string) => `Category for ${m} on ${date}`,
  },
  budgets: {
    heading: "Budgets this pay cycle",
    intro: "Budgets are per pay cycle. Set one for any category you want to keep an eye on.",
    summary: (spent: string, budget: string) => `${spent} spent of ${budget} budgeted`,
    summaryNote: (n: number) => (n === 1 ? "Across 1 budgeted category" : `Across ${n} budgeted categories`),
    none: "No budgets yet. Set one on any category below.",
    suggestIntro: "Some ideas from your last three pay cycles. Set one, change the amount, or skip it.",
    suggest: (avg: string, amt: string) => `you average ${avg} a pay cycle. Set a ${amt} budget?`,
    set: "Set",
    setSr: (amt: string, name: string) => `Set a ${amt} budget for ${name}`,
    adjust: "Adjust",
    dismiss: "Dismiss",
    noBudget: "No budget",
    editTitle: (cat: string) => `${cat} budget`,
    amountLabel: "Budget per pay cycle",
    amountHint: (avg: string) => `You've averaged ${avg} a pay cycle over the last 3 pay cycles.`,
    amountHintNone: "No spending in this category over the last 3 pay cycles.",
    save: "Save budget",
    remove: "Remove budget",
    saved: (cat: string) => `${cat} budget saved`,
    removed: (cat: string) => `${cat} budget removed`,
    invalid: "Enter an amount of $0 or more, like 200",
    otherCategories: "Other categories",
  },
  compareLink: "Compare with past pay cycles",
  calendarLink: "Open calendar",
  subscriptionsLink: "Subscriptions",
} as const;

export const compare = {
  title: "Spending comparison",
  intro: "Context for your spending, not a league table.",
  tabsLabel: "Compare with",
  tabs: { history: "Your last 3 pay cycles", cohort: "People in a similar situation" },
  history: {
    note: (days: number) => `This pay cycle so far covers ${days} of 14 days.`,
    thisCycle: "This pay cycle so far",
    average: "Average of last 3",
    cycles: "Last 3 pay cycles",
    cycleLabel: (start: string) => `From ${start}`,
    notEnough: "We need at least one full pay cycle of history to compare.",
  },
  cohort: {
    intro: "How your spending compares with people in a similar situation (age, income, region).",
    incomeBand: (from: string, to: string) => `${from}–${to} a month`,
    who: (age: string, income: string, region: string) => `People aged ${age}, earning ${income}, in ${region}.`,
    you: "You",
    typical: "Typical range",
    middle: "Middle",
    perCycle: "Per pay cycle, your average over the last 3 pay cycles.",
    excluded: "Gambling, alcohol and borrowing aren't compared.",
    sample: "Sample cohort data",
    row: (name: string, you: string, low: string, high: string, mid: string) =>
      `${name}: you ${you}. Typical range ${low} to ${high}, middle ${mid}.`,
    notEnough: "We need at least one full pay cycle of history to compare.",
  },
} as const;

export const calendarPage = {
  /** UX round 2, 5.1: the fortnight's balance as a line. */
  chart: {
    heading: "Balance",
    today: "Today",
    confirmed: "Confirmed",
    forecast: "Forecast",
    belowLegend: "Below $0",
    payLegend: "Payday",
    lowestLegend: "Lowest point",
    lowest: (amt: string, day: string) => `Lowest ${amt} · ${day}`,
    summary: (from: string, to: string, low: string, lowDay: string, belowDay: string | null) =>
      `End-of-day balance from ${from} to ${to}. Lowest ${low} on ${lowDay}.${belowDay ? ` Forecast to go below $0 on ${belowDay}.` : ""} The list has every figure.`,
  },
  /** 08/10/2026: the answer first. Same figures as the chart, grid and timeline. */
  headline: {
    short: (amt: string, day: string, daysBefore: number | null) =>
      `You'll be about ${amt} short on ${day}${daysBefore === 1 ? ", the day before payday" : daysBefore ? `, ${daysBefore} days before payday` : ""}.`,
    covered: (low: string, day: string, payday: string | null) =>
      payday ? `Lowest point ${low} on ${day} — you're covered until payday ${payday}.` : `Lowest point ${low} on ${day} — you stay above $0 as far as we can forecast.`,
    past: (low: string, day: string, closing: string) => `Lowest point ${low} on ${day}. You ended on ${closing}.`,
    bills: (amt: string, n: number, beforePayday: boolean) => `${amt} in bills ${beforePayday ? "before payday" : "still to come"} · ${n === 1 ? "1 bill" : `${n} bills`}`,
    noBills: (beforePayday: boolean) => (beforePayday ? "No bills predicted before payday" : "No bills predicted"),
    spent: (amt: string, n: number) => `${amt} spent · ${n === 1 ? "1 transaction" : `${n} transactions`}`,
    none: "We can't work out a balance for this period.",
    estimate: "Forecasts include predicted bills and expected pay, not everyday spending.",
    options: "Options if money's tight",
  },
  timeline: {
    heading: "Money in and out",
    pay: "Pay",
    spending: (n: number) => (n === 1 ? "Spending · 1 transaction" : `Spending · ${n} transactions`),
    predicted: "predicted",
    expected: "expected",
    lowest: "Lowest point",
    today: "Today",
    below: "Below $0",
    noMovement: "No money in or out",
    balanceSr: (amt: string, forecast: boolean) => `${forecast ? "Forecast balance" : "End-of-day balance"} ${amt}`,
    nextPayday: "Next payday",
    opensNext: "Opens the next fortnight",
    forecastEnds: (day: string) => `From ${day}: forecast not available yet. We forecast to the end of your next pay cycle.`,
    empty: "Nothing happened in this period.",
  },
  showAs: "Show as",
  showAsOptions: { list: "List", calendar: "Calendar" },
  gridForecastEnds: (day: string) => `From ${day} there's no forecast yet, so those days are blank.`,
  title: "Calendar",
  info: "About the calendar",
  infoBody: [
    "The list shows each payday, bill and day of spending in date order, with your balance at the end of each day.",
    "After today, balances are forecasts. They include predicted bills and expected pay, not everyday spending.",
    "In the calendar, a solid dot is spending that's gone through. A hollow dot is a bill we expect, based on past payments; bills of $100 or more show their amount.",
  ],
  viewLabel: "Calendar view",
  views: { fortnight: "Fortnight", month: "Month" },
  prev: "Previous",
  next: "Next",
  prevFortnight: "Previous fortnight",
  nextFortnight: "Next fortnight",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  range: (a: string, b: string) => `${a} – ${b}`,
  legend: {
    spend: "Spending", bill: "Predicted bill", bigBill: "Bill of $100 or more", below: "Below $0", close: "Close to $0", lowest: "Lowest point", payday: "Payday",
    note: "Numbers are end-of-day balances. After today they're forecasts.",
  },
  today: (day: string) => `Today · ${day}`,
  confirmed: "confirmed",
  forecast: "forecast",
  noBalance: "No balance for this day",
  selectRange: "Select a range",
  cancelRange: "Cancel range",
  rangeHint: "Tap a start day, then an end day.",
  rangeHintEnd: "Now tap an end day.",
  rangeTitle: (a: string, b: string) => `${a} – ${b}`,
  rangeSpent: "Spent",
  rangeBills: "Predicted bills",
  rangeIncome: "Paid in",
  rangeExpected: "Expected income",
  rangeDays: (n: number) => (n === 1 ? "1 day" : `${n} days`),
  clearRange: "Clear range",
  day: {
    spent: "Spent",
    transactions: "Transactions",
    paidIn: "Paid in",
    noSpend: "No spending on this day.",
    future: "This day hasn't happened yet.",
    bills: "Predicted bills",
    income: "Expected income",
    balance: "End-of-day balance",
    equation: (from: string, items: string, to: string) => `${from} ${items} = ${to}`,
    seeSpending: "See spending for this pay cycle",
    hardship: "Options if money's tight",
    predictedNote: "Predicted from past payments. It hasn't gone through.",
  },
} as const;

export const subscriptionsPage = {
  title: "Subscriptions",
  intro: "Regular charges we've found in your account.",
  total: (perCycle: string, perYear: string) => `About ${perCycle} a pay cycle · ${perYear} a year`,
  count: (n: number) => (n === 1 ? "1 subscription" : `${n} subscriptions`),
  perCycleShort: "a pay cycle",
  perYearLine: (amt: string) => `${amt} a year`,
  perYearShort: (amt: string) => `${amt} a year`,
  railLabel: "Subscription totals",
  notUsingHeading: "You said you don't use",
  notUsingNone: "Answer \"Still using it?\" on a subscription and any you don't use show here, with what cancelling would save.",
  notUsingSaving: (amt: string) => `Cancelling these would save about ${amt} a year`,
  moreFor: (m: string) => `More options for ${m}`,
  changeAnswer: "Change my answer",
  cancelledState: "You've cancelled this. We'll check it doesn't charge again.",
  amount: (amt: string, cadence: string) => `${amt} ${cadence}`,
  cadence: { monthly: "a month" },
  lastCharged: (date: string) => `Last charged ${date}`,
  nextCharge: (date: string) => `Next expected ${date}`,
  perCycle: (amt: string) => `${amt} a pay cycle`,
  perYear: (amt: string) => `${amt} a year`,
  keep: "Keep",
  kept: "Kept",
  keptToast: (m: string) => `${m} marked as kept`,
  remind: "Remind me before next charge",
  reminderSet: (date: string) => `Reminder set for ${date}`,
  reminderToast: (m: string, date: string) => `We'll remind you about ${m} on ${date}`,
  cancelReminder: "Cancel reminder",
  howToCancel: "How to cancel",
  undo: "Undo",
  cancelTitle: (m: string) => `How to cancel ${m}`,
  cancelSteps: (m: string, next: string) => [
    `Sign in to ${m} on its website or app.`,
    "Go to your account, membership or billing settings.",
    "Choose cancel, and follow the steps until you see a confirmation.",
    `You'll usually keep access until the end of what you've paid for. The next charge is expected around ${next}.`,
  ],
  cancelStore: "If you signed up through Apple or Google, cancel it in your phone's subscription settings instead.",
  cancelAfter: "Tippla can't cancel it for you. Once it's cancelled, it drops off this list after its next expected date passes.",
  empty: "We haven't found any regular subscriptions.",
  emptyAction: "Review transactions",
} as const;
