// Today page copy (redesign 07/10/2026). Shortened from the cards it replaces, same meaning: no new claims.
// en-AU; the banned-phrase test scans this file.
export const todayCopy = {
  hero: {
    label: "This pay cycle",
    cycle: (from: string, to: string) => `Pay cycle ${from} – ${to}`,
    pill: { short: "Short before payday", tight: "Tight", onTrack: "On track" },
    // Headline explanations (the amount sits above each).
    shortLine: "short of what's due before payday on",
    shortSr: (amt: string, payday: string) => `About ${amt} short of what's due before payday on ${payday}`,
    tightLine: "left after bills, with nothing spare before payday on",
    tightSr: (amt: string, payday: string) => `About ${amt} left after bills, with nothing spare before payday on ${payday}`,
    onTrackLine: "a day safe to spend until payday on",
    onTrackSr: (amt: string, payday: string) => `About ${amt} a day safe to spend until payday on ${payday}`,
    leftLine: "left after bills before payday on",
    leftSr: (amt: string, payday: string) => `About ${amt} left after bills before payday on ${payday}`,
    daysToPayday: "Days to payday",
    daysLeft: (n: number) => (n === 1 ? "1 left" : `${n} left`),
    paydayToday: "Payday today",
    daysSr: (n: number, total: number) => `Day ${total - n} of ${total} in this pay cycle; ${n === 1 ? "1 day" : `${n} days`} to payday`,
    balance: "Balance",
    due: "Due before payday",
    covered: (amt: string) => `Covered ${amt}`,
    short: (amt: string) => `Short ${amt}`,
    left: (amt: string) => `Left ${amt}`,
    barSr: (balance: string, due: string, rest: string, short: boolean) =>
      due === "$0" ? `Nothing due before payday; balance ${balance}` : short ? `Balance covers ${balance} of ${due} due; ${rest} short` : `Balance ${balance} covers the ${due} due; ${rest} left`,
    nothingDue: "Nothing due before payday",
    more: (n: number) => `and ${n} more`,
    paidIn: "Paid in",
    spent: "Spent",
    advance: "Pay advance (not income)",
    advanceBack: (amt: string, date: string) => `${amt} back ${date}`,
    seeWhatsDue: "See what's due",
    moneyTight: "Options if money's tight",
    ask: "Ask Tippla",
    estimate: "Estimate",
    how: "How we worked this out",
    sevenDays: "For the next 7 days",
  },
  quick: {
    label: "Quick actions",
    bills: "Bills due",
    pause: "Pause payment",
    ask: "Ask Tippla",
    plan: "Your plan",
    hardship: "Hardship help",
  },
  needs: {
    heading: "Needs a look",
    seeAll: "See all",
    showFewer: "Show fewer",
    count: (n: number) => (n === 1 ? "1 item" : `${n} items`),
    more: (title: string) => `More actions: ${title}`,
    swipeHint: "Swipe left for Snooze and Done",
    allClear: (checked: string) => `Nothing needs a look right now. ${checked}.`,
    moreToLook: (n: number) => (n === 1 ? "1 more to look at" : `${n} more to look at`),
    open: "Open",
  },
  score: {
    heading: "SmartScore",
    details: "Details",
    gaugeSr: (score: number, band: string) => `SmartScore ${score} out of 1,000, ${band}`,
    since: (delta: string, date: string) => `${delta} since ${date}`,
    steady: (date: string) => `Steady since ${date}`,
    toNext: (pts: number, band: string, at: number) => `${pts} points to ${band} at ${at}`,
    top: "Top of the scale",
    trendSr: (from: number, to: number) => `SmartScore trend from ${from} to ${to}`,
    bandsLabel: "SmartScore bands",
    estimated: "Estimated",
    open: "Open SmartScore",
  },
  plan: {
    step: (n: number, of: number) => `Your plan · Step ${n} of ${of}`,
    nextStep: "Your next step",
    pickGoal: "Pick a goal",
    changeGoal: "Change goal",
    estimateLabel: "SmartScore could reach",
    estimateBy: (date: string) => `by ${date} · estimate`,
    seeHow: "See how",
    seePlan: "See your plan",
    planName: (title: string) => `Your plan ${title}`,
    progress: "Your progress",
    goalLine: (goal: string) => `Your goal: ${goal}`,
    stepGoal: (step: string) => `Goal for this step: ${step[0]!.toLowerCase()}${step.slice(1)}.`,
  },
  coming: {
    heading: "Coming up",
    beforePayday: (day: string) => `Before payday · ${day}`,
    balanceNow: "Balance now",
    left: (amt: string) => `${amt} left`,
    belowZero: "This takes you below $0",
    seeOptions: "See your options",
    shortBefore: "Short before payday",
    leftBefore: "Left before payday",
    paydayRow: (payer: string) => `Payday · ${payer}`,
    afterPayday: "After payday",
    afterSummary: (n: number, left: string, day: string) => `${n === 1 ? "1 bill" : `${n} bills`}, ${left} left by ${day}`,
    show: "Show",
    hide: "Hide",
    advanceSub: "pay advance repayment",
    pauseThisMonth: "Pause this month",
    leftSr: (amt: string) => `, ${amt} left after it`,
    calendar: "Calendar",
    seeCalendar: "See calendar",
    none: "Nothing due in the next two weeks.",
    payday: "Payday",
    advanceRepay: "Pay advance repayment",
    tippla: "Tippla membership",
    qualifier: { predicted: "predicted", confirmed: "confirmed", expected: "expected", estimated: "estimated", pausable: "can be paused" } as Record<string, string>,
  },
  spending: {
    heading: "Spending",
    byDay: (day: number, of: number) => `by day ${day} of ${of}`,
    more: (amt: string) => `${amt} more than at this point last cycle`,
    less: (amt: string) => `${amt} less than at this point last cycle`,
    same: "About the same as at this point last cycle",
    usually: (amt: string) => `Your full cycle is usually about ${amt}`,
    fixed: "Fixed costs",
    repayments: "Repayments",
    fixedSame: "same",
    everyday: "Everyday spending",
    otherN: (n: number) => `Other (${n} ${n === 1 ? "category" : "categories"})`,
    changeSr: (amt: string, up: boolean) => `${up ? "up" : "down"} ${amt} since this point last cycle`,
    sameSr: "same as this point last cycle",
    sinceLast: "Since this point last cycle",
    explore: "Explore spending",
    /** Same time frame as the Spending page: pay cycles, never calendar months (UX round 2, 1.1). */
    cycle: (start: string, end: string, day: number, of: number) => `This pay cycle ${start} – ${end} · day ${day} of ${of}`,
    soFar: "spent so far this pay cycle",
    average: (amt: string) => `avg ${amt}`,
    averageChip: (amt: string, n: number) => `Average ${amt} a pay cycle over the last ${n}`,
    barsSr: (rows: string) => `Spending per pay cycle: ${rows}`,
    barLabel: (start: string) => start,
    now: "Now",
    where: "Where it went this pay cycle",
    splitSr: (rows: string) => `Spending by category this pay cycle: ${rows}`,
    other: "Other",
    otherHint: (n: number) => `${n} more ${n === 1 ? "category" : "categories"}: opens all categories`,
    openHint: "See transactions",
    noData: "No data",
  },
  sections: {
    now: { title: "Before payday", desc: "Where you stand and what's due" },
    cycle: { title: "This cycle", desc: "Where your money is going" },
    longer: { title: "Longer term", desc: "Your SmartScore and plan" },
    chips: { now: "Before payday", cycle: "This cycle", longer: "Longer term" },
    label: "Sections",
  },
  progress: {
    choosePlan: "Choose a plan",
    choosePlanBody: "Pick one thing to work on. We'll break it into small steps.",
    heading: "Your progress",
    details: "Details",
    detailsSr: ": your progress, goal and SmartScore timeline",
    estimated: "estimated",
  },
  unusual: {
    heading: (day: string) => `Was ${day} unusual?`,
  },
  askPlaceholder: "Ask Tippla anything",
};
