// Today page copy (redesign 07/10/2026). Shortened from the cards it replaces, same meaning: no new claims.
// en-AU; the banned-phrase test scans this file.
export const todayCopy = {
  hero: {
    label: "This pay cycle",
    cycle: (from: string, to: string) => `Pay cycle ${from} – ${to}`,
    pill: { short: "Short before payday", tight: "Tight", onTrack: "On track" },
    // Headline explanations (the amount sits above each).
    shortLine: "short of what's due before payday on",
    shortSr: (amt: string, payday: string) => `About ${amt} short of what's due before payday on ${payday}`,
    tightLine: "left after bills, with nothing spare before payday on",
    tightSr: (amt: string, payday: string) => `About ${amt} left after bills, with nothing spare before payday on ${payday}`,
    onTrackLine: "a day safe to spend until payday on",
    onTrackSr: (amt: string, payday: string) => `About ${amt} a day safe to spend until payday on ${payday}`,
    leftLine: "left after bills before payday on",
    leftSr: (amt: string, payday: string) => `About ${amt} left after bills before payday on ${payday}`,
    daysToPayday: "Days to payday",
    daysLeft: (n: number) => (n === 1 ? "1 left" : `${n} left`),
    paydayToday: "Payday today",
    daysSr: (n: number, total: number) => `Day ${total - n} of ${total} in this pay cycle; ${n === 1 ? "1 day" : `${n} days`} to payday`,
    balance: "Balance",
    due: "Due before payday",
    covered: (amt: string) => `Covered ${amt}`,
    short: (amt: string) => `Short ${amt}`,
    left: (amt: string) => `Left ${amt}`,
    barSr: (balance: string, due: string, rest: string, short: boolean) =>
      due === "$0" ? `Nothing due before payday; balance ${balance}` : short ? `Balance covers ${balance} of ${due} due; ${rest} short` : `Balance ${balance} covers the ${due} due; ${rest} left`,
    nothingDue: "Nothing due before payday",
    more: (n: number) => `and ${n} more`,
    paidIn: "Paid in",
    spent: "Spent",
    advance: "Pay advance (not income)",
    advanceBack: (amt: string, date: string) => `${amt} back ${date}`,
    seeWhatsDue: "See what's due",
    moneyTight: "Options if money's tight",
    estimate: "Estimate",
    how: "How we worked this out",
    sevenDays: "For the next 7 days",
  },
  quick: {
    label: "Quick actions",
    bills: "Bills due",
    pause: "Pause payment",
    ask: "Ask Tippla",
    plan: "Your plan",
    hardship: "Hardship help",
  },
  needs: {
    heading: "Needs a look",
    seeAll: "See all",
    showFewer: "Show fewer",
    count: (n: number) => (n === 1 ? "1 item" : `${n} items`),
    more: (title: string) => `More actions: ${title}`,
    swipeHint: "Swipe left for Snooze and Done",
    allClear: (checked: string) => `Nothing needs a look right now. ${checked}.`,
    open: "Open",
  },
  score: {
    heading: "SmartScore",
    details: "Details",
    gaugeSr: (score: number, band: string) => `SmartScore ${score} out of 1,000, ${band}`,
    since: (delta: string, date: string) => `${delta} since ${date}`,
    steady: (date: string) => `Steady since ${date}`,
    toNext: (pts: number, band: string, at: number) => `${pts} points to ${band} at ${at}`,
    top: "Top of the scale",
    trendSr: (from: number, to: number) => `SmartScore trend from ${from} to ${to}`,
    bandsLabel: "SmartScore bands",
    estimated: "Estimated",
    open: "Open SmartScore",
  },
  plan: {
    step: (n: number, of: number) => `Your plan · Step ${n} of ${of}`,
    nextStep: "Your next step",
    pickGoal: "Pick a goal",
    changeGoal: "Change goal",
    estimateLabel: "SmartScore could reach",
    estimateBy: (date: string) => `by ${date} · estimate`,
    seeHow: "See how",
    seePlan: "See your plan",
    planName: (title: string) => `Your plan ${title}`,
    progress: "Your progress",
    goalLine: (goal: string) => `Your goal: ${goal}`,
    stepGoal: (step: string) => `Goal for this step: ${step[0]!.toLowerCase()}${step.slice(1)}.`,
  },
  coming: {
    heading: "Coming up",
    calendar: "Calendar",
    seeCalendar: "See calendar",
    none: "Nothing due in the next two weeks.",
    payday: "Payday",
    advanceRepay: "Pay advance repayment",
    tippla: "Tippla membership",
    qualifier: { predicted: "predicted", confirmed: "confirmed", expected: "expected", estimated: "estimated", pausable: "can be paused" } as Record<string, string>,
  },
  spending: {
    heading: "Spending",
    explore: "Explore spending",
    range: (from: string, to: string, partial: string | null) => `${from} – ${to}${partial ? ` · ${partial}` : ""}`,
    partial: (month: string, date: string) => `${month} to ${date}`,
    soFar: (month: string) => `so far in ${month}`,
    inMonth: (month: string) => `in ${month}`,
    average: (amt: string) => `avg ${amt}`,
    averageChip: (amt: string, n: number) => `Average ${amt} a month over ${n} months`,
    under: (amt: string, n: number) => `${amt} under your ${n}-month average`,
    over: (amt: string, n: number) => `${amt} over your ${n}-month average`,
    barsSr: (rows: string) => `Monthly spending: ${rows}`,
    where: (month: string) => `Where it went in ${month}`,
    splitSr: (rows: string) => `Spending by group: ${rows}`,
    groups: { bills: "Bills & housing", groceries: "Groceries", shopping: "Shopping", eatingOut: "Eating out", transport: "Transport", gambling: "Gambling", other: "Other" } as Record<string, string>,
    noData: "No data",
  },
  unusual: {
    heading: (day: string) => `Was ${day} unusual?`,
  },
  askPlaceholder: "Ask Tippla about bills, spending or score",
};
