// Turns design/tokens.json (or tokens.template.json until Astra delivers) into CSS variables.
// Output: src/styles/tokens.css. Run automatically before dev and build.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const real = path.join(root, "design/tokens.json");
const src = fs.existsSync(real) ? real : path.join(root, "design/tokens.template.json");
const t = JSON.parse(fs.readFileSync(src, "utf8"));

const kebab = (s) => s.replace(/_/g, "-").replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const vars = (obj, prefix) =>
  Object.entries(obj)
    .filter(([k]) => !k.startsWith("_"))
    .map(([k, v]) => `  --${prefix}-${kebab(k)}: ${v};`);

// ---- Contrast-safe dimming (components.md §07): blend each category colour towards surface,
// starting at alpha 0.50 and stepping 0.005 until it reaches 3.05:1 against surface AND surface2.
const hex = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const toHex = (rgb) => "#" + rgb.map((v) => Math.round(v).toString(16).padStart(2, "0")).join("").toUpperCase();
const lin = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4; };
const lum = ([r, g, b]) => 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };
function dimmed(colour, surface, surface2) {
  const c = hex(colour), s = hex(surface), s2 = hex(surface2);
  for (let a = 0.5; a <= 1.0001; a += 0.005) {
    const mix = c.map((v, i) => Math.round(v * a + s[i] * (1 - a)));
    if (ratio(mix, s) >= 3.05 && ratio(mix, s2) >= 3.05) return toHex(mix);
  }
  return colour;
}

function theme(mode) {
  const c = t.color;
  const cats = Object.entries(c.category[mode]).filter(([k]) => !k.startsWith("_"));
  return [
    ...vars(c[mode], "color"),
    ...vars(c.stage[mode], "stage"),
    ...vars(c.category[mode], "cat"),
    ...cats.map(([k, v]) => `  --cat-dim-${kebab(k)}: ${dimmed(v, c[mode].surface, c[mode].surface2)};`),
    ...(c.chart ? vars(c.chart[mode], "chart") : []),
    ...(c.spend ? vars(c.spend[mode], "spend") : []),
    ...(c.band ? vars(c.band[mode], "band") : []),
    ...Object.entries(t.elevation[mode]).map(([k, v]) => `  --elev-${k}: ${v};`),
  ].join("\n");
}

const f = t.font;
const shared = [
  `  --font-display: '${f.display.family}', ${f.display.fallback};`,
  `  --font-body: '${f.body.family}', ${f.body.fallback};`,
  `  --font-numeric: '${f.numeric.family}', ${f.numeric.fallback};`,
  `  --motion-fast: ${t.motion.fast}ms;`,
  `  --motion-base: ${t.motion.base}ms;`,
  `  --motion-slow: ${t.motion.slow}ms;`,
  `  --motion-easing: ${t.motion.easing};`,
  `  --focus-width: ${t.focusRing?.width ?? 2}px;`,
  `  --focus-offset: ${t.focusRing?.offset ?? 2}px;`,
  `  --gutter: ${t.layout.gutter}px;`,
  ...(c => c ? [
    `  --hero-gradient: linear-gradient(135deg, ${c.from} 0%, ${c.mid} 55%, ${c.to} 100%);`,
    `  --cta-gradient: linear-gradient(90deg, ${c.ctaFrom} 0%, ${c.ctaTo} 100%);`,
    `  --hero-on: ${c.on};`, `  --hero-on-muted: ${c.onMuted};`, `  --hero-negative-mark: ${c.negativeMark};`,
  ] : [])(t.color.hero),
  `  --tab-bar-height: ${t.layout.tabBarHeight}px;`,
  `  --sidebar-width: ${t.layout.desktopSidebar}px;`,
  `  --drawer-width: ${t.layout.drawerWidth}px;`,
  // Fixed brand surface: the light stage colours in BOTH themes, with light onAccent content.
  `  --brand-from: ${t.color.stage.light.steadying};`,
  `  --brand-to: ${t.color.stage.light.thriving};`,
  `  --brand-on: ${t.color.light.onAccent};`,
  `  --brand-track: ${t.color.stage.light.building};`,
  `  color-scheme: light;`,
].join("\n");

// [data-theme] works on any element, so a page can show light and dark panes side by side.
// Page gutter: 16px on phones, then wider on tablet and desktop.
const gutters = t.layout.gutterTablet ? `
@media (min-width: 640px) { :root { --gutter: ${t.layout.gutterTablet}px; } }
@media (min-width: ${t.layout.breakpoints?.desktop ?? 1024}px) { :root { --gutter: ${t.layout.gutterDesktop}px; } }` : "";

const css = `/* GENERATED by scripts/tokens-to-css.mjs from ${path.relative(root, src)}. Do not edit. */
:root {
${shared}
${theme("light")}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${theme("dark").replace(/^/gm, "  ")}
  }
}
[data-theme="light"] {
  color-scheme: light;
${theme("light")}
}
[data-theme="dark"] {
  color-scheme: dark;
${theme("dark")}
}${gutters}
`;
fs.writeFileSync(path.join(root, "src/styles/tokens.css"), css);

// Google Fonts stylesheet for whichever families the tokens name (so a new direction needs no code change).
const families = [...new Set([f.display, f.body, f.numeric].filter((x) => x.source === "Google Fonts" || !x.source).map((x) => x.family))];
const weights = [...new Set(Object.values(t.type).filter((v) => typeof v === "object").map((v) => v.weight))].sort((a, b) => a - b);
const href = `https://fonts.googleapis.com/css2?${families.map((fam) => `family=${fam.replace(/ /g, "+")}:wght@${weights.join(";")}`).join("&")}&display=swap`;
fs.writeFileSync(path.join(root, "src/styles/fonts.json"), JSON.stringify({ _generated: "scripts/tokens-to-css.mjs", href }, null, 2) + "\n");
console.log(`tokens.css written from ${path.relative(root, src)}`);
