// Turns design/tokens.json (or tokens.template.json until Astra delivers) into CSS variables.
// Output: src/styles/tokens.css. Run automatically before dev and build.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const real = path.join(root, "design/tokens.json");
const src = fs.existsSync(real) ? real : path.join(root, "design/tokens.template.json");
const t = JSON.parse(fs.readFileSync(src, "utf8"));

const kebab = (s) => s.replace(/_/g, "-").replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const vars = (obj, prefix) =>
  Object.entries(obj)
    .filter(([k]) => !k.startsWith("_"))
    .map(([k, v]) => `  --${prefix}-${kebab(k)}: ${v};`);

function theme(mode) {
  const c = t.color;
  return [
    ...vars(c[mode], "color"),
    ...vars(c.stage[mode], "stage"),
    ...vars(c.category[mode], "cat"),
    ...(c.chart ? vars(c.chart[mode], "chart") : []),
    ...Object.entries(t.elevation[mode]).map(([k, v]) => `  --elev-${k}: ${v};`),
  ].join("\n");
}

const f = t.font;
const shared = [
  `  --font-display: '${f.display.family}', ${f.display.fallback};`,
  `  --font-body: '${f.body.family}', ${f.body.fallback};`,
  `  --font-numeric: '${f.numeric.family}', ${f.numeric.fallback};`,
  `  --motion-fast: ${t.motion.fast}ms;`,
  `  --motion-base: ${t.motion.base}ms;`,
  `  --motion-slow: ${t.motion.slow}ms;`,
  `  --motion-easing: ${t.motion.easing};`,
  `  color-scheme: light;`,
].join("\n");

const css = `/* GENERATED by scripts/tokens-to-css.mjs from ${path.relative(root, src)}. Do not edit. */
:root {
${shared}
${theme("light")}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${theme("dark").replace(/^/gm, "  ")}
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
${theme("dark")}
}
`;
fs.writeFileSync(path.join(root, "src/styles/tokens.css"), css);

// Google Fonts stylesheet for whichever families the tokens name (so a new direction needs no code change).
const families = [...new Set([f.display, f.body, f.numeric].filter((x) => x.source === "Google Fonts" || !x.source).map((x) => x.family))];
const weights = [...new Set(Object.values(t.type).filter((v) => typeof v === "object").map((v) => v.weight))].sort((a, b) => a - b);
const href = `https://fonts.googleapis.com/css2?${families.map((fam) => `family=${fam.replace(/ /g, "+")}:wght@${weights.join(";")}`).join("&")}&display=swap`;
fs.writeFileSync(path.join(root, "src/styles/fonts.json"), JSON.stringify({ _generated: "scripts/tokens-to-css.mjs", href }, null, 2) + "\n");
console.log(`tokens.css written from ${path.relative(root, src)}`);
